---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: "escape-cli"
    main: ./cmd/main.go
    ldflags:
      - -s -w -X github.com/Escape-Technologies/cli/pkg/cli.version={{.Version}} -X github.com/Escape-Technologies/cli/pkg/cli.commit={{.ShortCommit}}
dockers:
  - image_templates:
      - "escapetech/app-cli:{{ .Version }}"
      - "escapetech/app-cli:latest-amd64"
    dockerfile: Dockerfile
    goarch: amd64
    build_flag_templates: 
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=app-cli"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - image_templates:
      - "escapetech/app-cli:{{ .Version }}"
      - "escapetech/app-cli:latest-arm64"
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates: 
    - "--pull"
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title=app-cli"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.licenses=Apache-2.0"

checksum:
  algorithm: sha256
