---
services:
  mtls-proxy:
    network_mode: host
    image: mitmproxy/mitmproxy:latest
    restart: always
    ports:
      - "7878:8080"
    command: "mitmdump --listen-host 0.0.0.0"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
