---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      {{- if .Values.ESCAPE_K8S_INTEGRATION }}
      serviceAccountName: {{ include "fullname" . }}
      {{- end }}
      containers:
        - name: {{ include "fullname" . }}
          image: {{ .Values.container.image }}
          args:
            - locations
            - start
            - "-v"
            - {{ .Values.ESCAPE_PRIVATE_LOCATION | default (.Release.Name) | quote }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ .Values.container.resources.cpu }}
              memory: {{ .Values.container.resources.memory }}
            requests:
              cpu: {{ .Values.container.resources.cpu }}
              memory: {{ .Values.container.resources.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 60
          env:
            - name: ESCAPE_HEALTH_CHECK_PORT
              value: '8080'
            - name: ESCAPE_API_KEY
              value: {{ .Values.ESCAPE_API_KEY | default "" | quote }}
            - name: ESCAPE_K8S_INTEGRATION
              value: {{ .Values.ESCAPE_K8S_INTEGRATION | quote }}
            {{- with .Values.container.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.container.extra }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
