/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4{}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 struct for CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
type CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 struct {
	Key string `json:"key"`
	Jq *string `json:"jq,omitempty"`
}

type _CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4

// NewCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 instantiates a new CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4(key string) *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 {
	this := CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4{}
	this.Key = key
	return &this
}

// NewCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4WithDefaults instantiates a new CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4WithDefaults() *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 {
	this := CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4{}
	return &this
}

// GetKey returns the Key field value
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) SetKey(v string) {
	o.Key = v
}

// GetJq returns the Jq field value if set, zero value otherwise.
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) GetJq() string {
	if o == nil || IsNil(o.Jq) {
		var ret string
		return ret
	}
	return *o.Jq
}

// GetJqOk returns a tuple with the Jq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) GetJqOk() (*string, bool) {
	if o == nil || IsNil(o.Jq) {
		return nil, false
	}
	return o.Jq, true
}

// HasJq returns a boolean if a field has been set.
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) HasJq() bool {
	if o != nil && !IsNil(o.Jq) {
		return true
	}

	return false
}

// SetJq gets a reference to the given string and assigns it to the Jq field.
func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) SetJq(v string) {
	o.Jq = &v
}

func (o CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Jq) {
		toSerialize["jq"] = o.Jq
	}
	return toSerialize, nil
}

func (o *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 := _CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4)

	if err != nil {
		return err
	}

	*o = CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4(varCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4)

	return err
}

type NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 struct {
	value *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
	isSet bool
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) Get() *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 {
	return v.value
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) Set(val *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4(val *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 {
	return &NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4{value: val, isSet: true}
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


