/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// checks if the GetLocation404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLocation404Response{}

// GetLocation404Response struct for GetLocation404Response
type GetLocation404Response struct {
	Message EnumNOTFOUND `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _GetLocation404Response GetLocation404Response

// NewGetLocation404Response instantiates a new GetLocation404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLocation404Response(message EnumNOTFOUND) *GetLocation404Response {
	this := GetLocation404Response{}
	this.Message = message
	return &this
}

// NewGetLocation404ResponseWithDefaults instantiates a new GetLocation404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLocation404ResponseWithDefaults() *GetLocation404Response {
	this := GetLocation404Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *GetLocation404Response) GetMessage() EnumNOTFOUND {
	if o == nil {
		var ret EnumNOTFOUND
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetLocation404Response) GetMessageOk() (*EnumNOTFOUND, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetLocation404Response) SetMessage(v EnumNOTFOUND) {
	o.Message = v
}

func (o GetLocation404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLocation404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetLocation404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLocation404Response := _GetLocation404Response{}

	err = json.Unmarshal(data, &varGetLocation404Response)

	if err != nil {
		return err
	}

	*o = GetLocation404Response(varGetLocation404Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetLocation404Response struct {
	value *GetLocation404Response
	isSet bool
}

func (v NullableGetLocation404Response) Get() *GetLocation404Response {
	return v.value
}

func (v *NullableGetLocation404Response) Set(val *GetLocation404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLocation404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLocation404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLocation404Response(val *GetLocation404Response) *NullableGetLocation404Response {
	return &NullableGetLocation404Response{value: val, isSet: true}
}

func (v NullableGetLocation404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLocation404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


