/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSchema200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSchema200Response{}

// UpdateSchema200Response struct for UpdateSchema200Response
type UpdateSchema200Response struct {
	Message string `json:"message"`
}

type _UpdateSchema200Response UpdateSchema200Response

// NewUpdateSchema200Response instantiates a new UpdateSchema200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSchema200Response(message string) *UpdateSchema200Response {
	this := UpdateSchema200Response{}
	this.Message = message
	return &this
}

// NewUpdateSchema200ResponseWithDefaults instantiates a new UpdateSchema200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSchema200ResponseWithDefaults() *UpdateSchema200Response {
	this := UpdateSchema200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *UpdateSchema200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UpdateSchema200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UpdateSchema200Response) SetMessage(v string) {
	o.Message = v
}

func (o UpdateSchema200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSchema200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *UpdateSchema200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSchema200Response := _UpdateSchema200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSchema200Response)

	if err != nil {
		return err
	}

	*o = UpdateSchema200Response(varUpdateSchema200Response)

	return err
}

type NullableUpdateSchema200Response struct {
	value *UpdateSchema200Response
	isSet bool
}

func (v NullableUpdateSchema200Response) Get() *UpdateSchema200Response {
	return v.value
}

func (v *NullableUpdateSchema200Response) Set(val *UpdateSchema200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSchema200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSchema200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSchema200Response(val *UpdateSchema200Response) *NullableUpdateSchema200Response {
	return &NullableUpdateSchema200Response{value: val, isSet: true}
}

func (v NullableUpdateSchema200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSchema200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


