/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateIntegrationRequestParametersDataOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIntegrationRequestParametersDataOneOf1{}

// CreateIntegrationRequestParametersDataOneOf1 struct for CreateIntegrationRequestParametersDataOneOf1
type CreateIntegrationRequestParametersDataOneOf1 struct {
	Kind string `json:"kind"`
	Parameters CreateIntegrationRequestParametersDataOneOf1Parameters `json:"parameters"`
}

type _CreateIntegrationRequestParametersDataOneOf1 CreateIntegrationRequestParametersDataOneOf1

// NewCreateIntegrationRequestParametersDataOneOf1 instantiates a new CreateIntegrationRequestParametersDataOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIntegrationRequestParametersDataOneOf1(kind string, parameters CreateIntegrationRequestParametersDataOneOf1Parameters) *CreateIntegrationRequestParametersDataOneOf1 {
	this := CreateIntegrationRequestParametersDataOneOf1{}
	this.Kind = kind
	this.Parameters = parameters
	return &this
}

// NewCreateIntegrationRequestParametersDataOneOf1WithDefaults instantiates a new CreateIntegrationRequestParametersDataOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIntegrationRequestParametersDataOneOf1WithDefaults() *CreateIntegrationRequestParametersDataOneOf1 {
	this := CreateIntegrationRequestParametersDataOneOf1{}
	return &this
}

// GetKind returns the Kind field value
func (o *CreateIntegrationRequestParametersDataOneOf1) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CreateIntegrationRequestParametersDataOneOf1) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CreateIntegrationRequestParametersDataOneOf1) SetKind(v string) {
	o.Kind = v
}

// GetParameters returns the Parameters field value
func (o *CreateIntegrationRequestParametersDataOneOf1) GetParameters() CreateIntegrationRequestParametersDataOneOf1Parameters {
	if o == nil {
		var ret CreateIntegrationRequestParametersDataOneOf1Parameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *CreateIntegrationRequestParametersDataOneOf1) GetParametersOk() (*CreateIntegrationRequestParametersDataOneOf1Parameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *CreateIntegrationRequestParametersDataOneOf1) SetParameters(v CreateIntegrationRequestParametersDataOneOf1Parameters) {
	o.Parameters = v
}

func (o CreateIntegrationRequestParametersDataOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIntegrationRequestParametersDataOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["parameters"] = o.Parameters
	return toSerialize, nil
}

func (o *CreateIntegrationRequestParametersDataOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"parameters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIntegrationRequestParametersDataOneOf1 := _CreateIntegrationRequestParametersDataOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateIntegrationRequestParametersDataOneOf1)

	if err != nil {
		return err
	}

	*o = CreateIntegrationRequestParametersDataOneOf1(varCreateIntegrationRequestParametersDataOneOf1)

	return err
}

type NullableCreateIntegrationRequestParametersDataOneOf1 struct {
	value *CreateIntegrationRequestParametersDataOneOf1
	isSet bool
}

func (v NullableCreateIntegrationRequestParametersDataOneOf1) Get() *CreateIntegrationRequestParametersDataOneOf1 {
	return v.value
}

func (v *NullableCreateIntegrationRequestParametersDataOneOf1) Set(val *CreateIntegrationRequestParametersDataOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIntegrationRequestParametersDataOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIntegrationRequestParametersDataOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIntegrationRequestParametersDataOneOf1(val *CreateIntegrationRequestParametersDataOneOf1) *NullableCreateIntegrationRequestParametersDataOneOf1 {
	return &NullableCreateIntegrationRequestParametersDataOneOf1{value: val, isSet: true}
}

func (v NullableCreateIntegrationRequestParametersDataOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIntegrationRequestParametersDataOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


