/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// checks if the GetIntegration200ResponseDataOneOf5Parameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIntegration200ResponseDataOneOf5Parameters{}

// GetIntegration200ResponseDataOneOf5Parameters struct for GetIntegration200ResponseDataOneOf5Parameters
type GetIntegration200ResponseDataOneOf5Parameters struct {
	ApiKey string `json:"api_key"`
	WorkspaceName string `json:"workspace_name"`
	RepositoryName string `json:"repository_name"`
	Username *string `json:"username,omitempty"`
	InstanceUrl *string `json:"instance_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetIntegration200ResponseDataOneOf5Parameters GetIntegration200ResponseDataOneOf5Parameters

// NewGetIntegration200ResponseDataOneOf5Parameters instantiates a new GetIntegration200ResponseDataOneOf5Parameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIntegration200ResponseDataOneOf5Parameters(apiKey string, workspaceName string, repositoryName string) *GetIntegration200ResponseDataOneOf5Parameters {
	this := GetIntegration200ResponseDataOneOf5Parameters{}
	this.ApiKey = apiKey
	this.WorkspaceName = workspaceName
	this.RepositoryName = repositoryName
	return &this
}

// NewGetIntegration200ResponseDataOneOf5ParametersWithDefaults instantiates a new GetIntegration200ResponseDataOneOf5Parameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIntegration200ResponseDataOneOf5ParametersWithDefaults() *GetIntegration200ResponseDataOneOf5Parameters {
	this := GetIntegration200ResponseDataOneOf5Parameters{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) SetApiKey(v string) {
	o.ApiKey = v
}

// GetWorkspaceName returns the WorkspaceName field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetWorkspaceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceName
}

// GetWorkspaceNameOk returns a tuple with the WorkspaceName field value
// and a boolean to check if the value has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetWorkspaceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceName, true
}

// SetWorkspaceName sets field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) SetWorkspaceName(v string) {
	o.WorkspaceName = v
}

// GetRepositoryName returns the RepositoryName field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetRepositoryName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepositoryName
}

// GetRepositoryNameOk returns a tuple with the RepositoryName field value
// and a boolean to check if the value has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetRepositoryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepositoryName, true
}

// SetRepositoryName sets field value
func (o *GetIntegration200ResponseDataOneOf5Parameters) SetRepositoryName(v string) {
	o.RepositoryName = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetIntegration200ResponseDataOneOf5Parameters) SetUsername(v string) {
	o.Username = &v
}

// GetInstanceUrl returns the InstanceUrl field value if set, zero value otherwise.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetInstanceUrl() string {
	if o == nil || IsNil(o.InstanceUrl) {
		var ret string
		return ret
	}
	return *o.InstanceUrl
}

// GetInstanceUrlOk returns a tuple with the InstanceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) GetInstanceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceUrl) {
		return nil, false
	}
	return o.InstanceUrl, true
}

// HasInstanceUrl returns a boolean if a field has been set.
func (o *GetIntegration200ResponseDataOneOf5Parameters) HasInstanceUrl() bool {
	if o != nil && !IsNil(o.InstanceUrl) {
		return true
	}

	return false
}

// SetInstanceUrl gets a reference to the given string and assigns it to the InstanceUrl field.
func (o *GetIntegration200ResponseDataOneOf5Parameters) SetInstanceUrl(v string) {
	o.InstanceUrl = &v
}

func (o GetIntegration200ResponseDataOneOf5Parameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIntegration200ResponseDataOneOf5Parameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key"] = o.ApiKey
	toSerialize["workspace_name"] = o.WorkspaceName
	toSerialize["repository_name"] = o.RepositoryName
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.InstanceUrl) {
		toSerialize["instance_url"] = o.InstanceUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetIntegration200ResponseDataOneOf5Parameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key",
		"workspace_name",
		"repository_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIntegration200ResponseDataOneOf5Parameters := _GetIntegration200ResponseDataOneOf5Parameters{}

	err = json.Unmarshal(data, &varGetIntegration200ResponseDataOneOf5Parameters)

	if err != nil {
		return err
	}

	*o = GetIntegration200ResponseDataOneOf5Parameters(varGetIntegration200ResponseDataOneOf5Parameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "api_key")
		delete(additionalProperties, "workspace_name")
		delete(additionalProperties, "repository_name")
		delete(additionalProperties, "username")
		delete(additionalProperties, "instance_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetIntegration200ResponseDataOneOf5Parameters struct {
	value *GetIntegration200ResponseDataOneOf5Parameters
	isSet bool
}

func (v NullableGetIntegration200ResponseDataOneOf5Parameters) Get() *GetIntegration200ResponseDataOneOf5Parameters {
	return v.value
}

func (v *NullableGetIntegration200ResponseDataOneOf5Parameters) Set(val *GetIntegration200ResponseDataOneOf5Parameters) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIntegration200ResponseDataOneOf5Parameters) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIntegration200ResponseDataOneOf5Parameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIntegration200ResponseDataOneOf5Parameters(val *GetIntegration200ResponseDataOneOf5Parameters) *NullableGetIntegration200ResponseDataOneOf5Parameters {
	return &NullableGetIntegration200ResponseDataOneOf5Parameters{value: val, isSet: true}
}

func (v NullableGetIntegration200ResponseDataOneOf5Parameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIntegration200ResponseDataOneOf5Parameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


