/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner{}

// CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner struct for CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner
type CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner struct {
	Username string `json:"username"`
	Headers map[string]string `json:"headers,omitempty"`
	Cookies map[string]string `json:"cookies,omitempty"`
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Scopes []string `json:"scopes,omitempty"`
	Audience *string `json:"audience,omitempty"`
}

type _CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner

// NewCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner instantiates a new CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner(username string, clientId string, clientSecret string) *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner {
	this := CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner{}
	this.Username = username
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInnerWithDefaults instantiates a new CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInnerWithDefaults() *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner {
	this := CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner{}
	return &this
}

// GetUsername returns the Username field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetUsername(v string) {
	o.Username = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetHeadersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetCookies returns the Cookies field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetCookies() map[string]string {
	if o == nil || IsNil(o.Cookies) {
		var ret map[string]string
		return ret
	}
	return o.Cookies
}

// GetCookiesOk returns a tuple with the Cookies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetCookiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Cookies) {
		return map[string]string{}, false
	}
	return o.Cookies, true
}

// HasCookies returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) HasCookies() bool {
	if o != nil && !IsNil(o.Cookies) {
		return true
	}

	return false
}

// SetCookies gets a reference to the given map[string]string and assigns it to the Cookies field.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetCookies(v map[string]string) {
	o.Cookies = v
}

// GetClientId returns the ClientId field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetScopes(v []string) {
	o.Scopes = v
}

// GetAudience returns the Audience field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetAudience() string {
	if o == nil || IsNil(o.Audience) {
		var ret string
		return ret
	}
	return *o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) GetAudienceOk() (*string, bool) {
	if o == nil || IsNil(o.Audience) {
		return nil, false
	}
	return o.Audience, true
}

// HasAudience returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) HasAudience() bool {
	if o != nil && !IsNil(o.Audience) {
		return true
	}

	return false
}

// SetAudience gets a reference to the given string and assigns it to the Audience field.
func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) SetAudience(v string) {
	o.Audience = &v
}

func (o CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Cookies) {
		toSerialize["cookies"] = o.Cookies
	}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Audience) {
		toSerialize["audience"] = o.Audience
	}
	return toSerialize, nil
}

func (o *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"client_id",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner := _CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner)

	if err != nil {
		return err
	}

	*o = CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner(varCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner)

	return err
}

type NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner struct {
	value *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner
	isSet bool
}

func (v NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) Get() *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner {
	return v.value
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) Set(val *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner(val *CreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) *NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner {
	return &NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner{value: val, isSet: true}
}

func (v NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationAuthenticationPresetsInnerOneOf2UsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


