/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner - struct for CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
type CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner struct {
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6
	CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfAsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfAsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6: v,
	}
}

// CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner is a convenience function that returns CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 wrapped in CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
func CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7AsCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(v *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7) CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{
		CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 = nil
	}

	// try to unmarshal data into CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7
	err = newStrictDecoder(data).Decode(&dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7)
	if err == nil {
		jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7, _ := json.Marshal(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7)
		if string(jsonCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7) == "{}" { // empty struct
			dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 = nil
		} else {
			if err = validator.Validate(dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7); err != nil {
				dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 = nil
		dst.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) MarshalJSON() ([]byte, error) {
	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6)
	}

	if src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 != nil {
		return json.Marshal(&src.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 != nil {
		return obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) GetActualInstanceValue() (interface{}) {
	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf1
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf2
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf3
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf4
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf6
	}

	if obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7 != nil {
		return *obj.CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf7
	}

	// all schemas are nil
	return nil
}

type NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner struct {
	value *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner
	isSet bool
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) Get() *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return v.value
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) Set(val *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner(val *CreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner {
	return &NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner{value: val, isSet: true}
}

func (v NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationRequestConfigurationCustomRulesInnerTransformMutateInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


