/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select{}

// CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select struct for CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select
type CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select struct {
	Type *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type `json:"type,omitempty"`
	Name *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key `json:"name,omitempty"`
	Value *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select

// NewCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select instantiates a new CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select() *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select {
	this := CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select{}
	return &this
}

// NewCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6SelectWithDefaults instantiates a new CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6SelectWithDefaults() *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select {
	this := CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetType() CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type {
	if o == nil || IsNil(o.Type) {
		var ret CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetTypeOk() (*CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type and assigns it to the Type field.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) SetType(v CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf16Type) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetName() CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key {
	if o == nil || IsNil(o.Name) {
		var ret CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetNameOk() (*CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key and assigns it to the Name field.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) SetName(v CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetValue() CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key {
	if o == nil || IsNil(o.Value) {
		var ret CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) GetValueOk() (*CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key and assigns it to the Value field.
func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) SetValue(v CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformTriggerInnerOneOf10Key) {
	o.Value = &v
}

func (o CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) UnmarshalJSON(data []byte) (err error) {
	varCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select := _CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select{}

	err = json.Unmarshal(data, &varCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select)

	if err != nil {
		return err
	}

	*o = CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select(varCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select struct {
	value *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select
	isSet bool
}

func (v NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) Get() *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select {
	return v.value
}

func (v *NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) Set(val *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select(val *CreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) *NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select {
	return &NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select{value: val, isSet: true}
}

func (v NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationRequestAnyOfConfigurationCustomRulesInnerTransformMutateInnerOneOf6Select) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


