/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5{}

// CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 struct for CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
type CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 struct {
	Value *string `json:"value,omitempty"`
	Values []string `json:"values,omitempty"`
	RegexReplace *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace `json:"regex_replace,omitempty"`
	Key string `json:"key"`
}

type _CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5

// NewCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 instantiates a new CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5(key string) *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 {
	this := CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5{}
	this.Key = key
	return &this
}

// NewCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5WithDefaults instantiates a new CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5WithDefaults() *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 {
	this := CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) SetValue(v string) {
	o.Value = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) SetValues(v []string) {
	o.Values = v
}

// GetRegexReplace returns the RegexReplace field value if set, zero value otherwise.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetRegexReplace() CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace {
	if o == nil || IsNil(o.RegexReplace) {
		var ret CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace
		return ret
	}
	return *o.RegexReplace
}

// GetRegexReplaceOk returns a tuple with the RegexReplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetRegexReplaceOk() (*CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace, bool) {
	if o == nil || IsNil(o.RegexReplace) {
		return nil, false
	}
	return o.RegexReplace, true
}

// HasRegexReplace returns a boolean if a field has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) HasRegexReplace() bool {
	if o != nil && !IsNil(o.RegexReplace) {
		return true
	}

	return false
}

// SetRegexReplace gets a reference to the given CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace and assigns it to the RegexReplace field.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) SetRegexReplace(v CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOfRegexReplace) {
	o.RegexReplace = &v
}

// GetKey returns the Key field value
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) SetKey(v string) {
	o.Key = v
}

func (o CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.RegexReplace) {
		toSerialize["regex_replace"] = o.RegexReplace
	}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 := _CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5)

	if err != nil {
		return err
	}

	*o = CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5(varCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5)

	return err
}

type NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 struct {
	value *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5
	isSet bool
}

func (v NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) Get() *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 {
	return v.value
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) Set(val *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5(val *CreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) *NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5 {
	return &NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5{value: val, isSet: true}
}

func (v NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationConfigurationRequestConfigurationCustomRulesInnerTransformMutateInnerOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


