---
ESCAPE_API_KEY: "00000000-0000-0000-0000-000000000000"

# You can set the private location name here
# or it will fallback to the helm release name
ESCAPE_PRIVATE_LOCATION: ""

# Enable/disable Kubernetes integration. (disables ClusterRole and ClusterRoleBinding)
ESCAPE_K8S_INTEGRATION: true

# Enable/disable forwarding mitm logs to the health check server (requires mitmproxy to be running with the addon)
ESCAPE_ENABLE_LOGS_ENDPOINT: false

# Disable color output in the cli
ESCAPE_COLOR_DISABLED: false

container:
  image: escapetech/cli:latest
  resources:
    cpu: "1"
    memory: "2Gi"
  env: []
  extra: {}
