/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6{}

// CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 struct for CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6
type CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 struct {
	Key EnumREQUESTOBJECT `json:"key"`
	Select CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select `json:"select"`
	Mutate CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate `json:"mutate"`
	AdditionalProperties map[string]interface{}
}

type _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6(key EnumREQUESTOBJECT, select_ CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select, mutate CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate) *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6{}
	this.Key = key
	this.Select = select_
	this.Mutate = mutate
	return &this
}

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6WithDefaults instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6WithDefaults() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6{}
	return &this
}

// GetKey returns the Key field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetKey() EnumREQUESTOBJECT {
	if o == nil {
		var ret EnumREQUESTOBJECT
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetKeyOk() (*EnumREQUESTOBJECT, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) SetKey(v EnumREQUESTOBJECT) {
	o.Key = v
}

// GetSelect returns the Select field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetSelect() CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select {
	if o == nil {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select
		return ret
	}

	return o.Select
}

// GetSelectOk returns a tuple with the Select field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetSelectOk() (*CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Select, true
}

// SetSelect sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) SetSelect(v CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Select) {
	o.Select = v
}

// GetMutate returns the Mutate field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetMutate() CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate {
	if o == nil {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate
		return ret
	}

	return o.Mutate
}

// GetMutateOk returns a tuple with the Mutate field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) GetMutateOk() (*CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mutate, true
}

// SetMutate sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) SetMutate(v CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6Mutate) {
	o.Mutate = v
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["select"] = o.Select
	toSerialize["mutate"] = o.Mutate

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"select",
		"mutate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 := _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6{}

	err = json.Unmarshal(data, &varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6)

	if err != nil {
		return err
	}

	*o = CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6(varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "select")
		delete(additionalProperties, "mutate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 struct {
	value *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6
	isSet bool
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) Get() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 {
	return v.value
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) Set(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6 {
	return &NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6{value: val, isSet: true}
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformMutateInnerOneOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


