/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the ListProfiles200ResponseDataInnerAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProfiles200ResponseDataInnerAsset{}

// ListProfiles200ResponseDataInnerAsset struct for ListProfiles200ResponseDataInnerAsset
type ListProfiles200ResponseDataInnerAsset struct {
	Id string `json:"id"`
	Class Enum42ef62c572640598bbdb83b930a50624 `json:"class"`
	Type Enum7c5a8d597678316a20092b786fdbb3dd `json:"type"`
	Uri string `json:"uri"`
	Name string `json:"name"`
	ExternalUrl string `json:"externalUrl"`
	FaviconUrl string `json:"faviconUrl"`
	Description string `json:"description"`
	CreatedAt string `json:"createdAt"`
	LastSeenAt string `json:"lastSeenAt"`
	ScheduledForDeletionAt string `json:"scheduledForDeletionAt"`
	Status Enum979d32dc69b8f72f50564e75367bcbb5 `json:"status"`
	Tags []ListProfiles200ResponseDataInnerAssetTagsInner `json:"tags"`
	Risks []Enum1ea54cdf1f4480ebf83fc671185f5693 `json:"risks"`
	FirstSeenScan ListProfiles200ResponseDataInnerAssetFirstSeenScan `json:"firstSeenScan"`
	LastSeenScan ListProfiles200ResponseDataInnerAssetFirstSeenScan `json:"lastSeenScan"`
	Service ListProfiles200ResponseDataInnerAssetService `json:"service"`
	Frontend ListProfiles200ResponseDataInnerAssetFrontend `json:"frontend"`
	Host ListProfiles200ResponseDataInnerAssetHost `json:"host"`
	Links ListProfiles200ResponseDataInnerAssetLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _ListProfiles200ResponseDataInnerAsset ListProfiles200ResponseDataInnerAsset

// NewListProfiles200ResponseDataInnerAsset instantiates a new ListProfiles200ResponseDataInnerAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProfiles200ResponseDataInnerAsset(id string, class Enum42ef62c572640598bbdb83b930a50624, type_ Enum7c5a8d597678316a20092b786fdbb3dd, uri string, name string, externalUrl string, faviconUrl string, description string, createdAt string, lastSeenAt string, scheduledForDeletionAt string, status Enum979d32dc69b8f72f50564e75367bcbb5, tags []ListProfiles200ResponseDataInnerAssetTagsInner, risks []Enum1ea54cdf1f4480ebf83fc671185f5693, firstSeenScan ListProfiles200ResponseDataInnerAssetFirstSeenScan, lastSeenScan ListProfiles200ResponseDataInnerAssetFirstSeenScan, service ListProfiles200ResponseDataInnerAssetService, frontend ListProfiles200ResponseDataInnerAssetFrontend, host ListProfiles200ResponseDataInnerAssetHost, links ListProfiles200ResponseDataInnerAssetLinks) *ListProfiles200ResponseDataInnerAsset {
	this := ListProfiles200ResponseDataInnerAsset{}
	this.Id = id
	this.Class = class
	this.Type = type_
	this.Uri = uri
	this.Name = name
	this.ExternalUrl = externalUrl
	this.FaviconUrl = faviconUrl
	this.Description = description
	this.CreatedAt = createdAt
	this.LastSeenAt = lastSeenAt
	this.ScheduledForDeletionAt = scheduledForDeletionAt
	this.Status = status
	this.Tags = tags
	this.Risks = risks
	this.FirstSeenScan = firstSeenScan
	this.LastSeenScan = lastSeenScan
	this.Service = service
	this.Frontend = frontend
	this.Host = host
	this.Links = links
	return &this
}

// NewListProfiles200ResponseDataInnerAssetWithDefaults instantiates a new ListProfiles200ResponseDataInnerAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProfiles200ResponseDataInnerAssetWithDefaults() *ListProfiles200ResponseDataInnerAsset {
	this := ListProfiles200ResponseDataInnerAsset{}
	return &this
}

// GetId returns the Id field value
func (o *ListProfiles200ResponseDataInnerAsset) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetId(v string) {
	o.Id = v
}

// GetClass returns the Class field value
func (o *ListProfiles200ResponseDataInnerAsset) GetClass() Enum42ef62c572640598bbdb83b930a50624 {
	if o == nil {
		var ret Enum42ef62c572640598bbdb83b930a50624
		return ret
	}

	return o.Class
}

// GetClassOk returns a tuple with the Class field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetClassOk() (*Enum42ef62c572640598bbdb83b930a50624, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Class, true
}

// SetClass sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetClass(v Enum42ef62c572640598bbdb83b930a50624) {
	o.Class = v
}

// GetType returns the Type field value
func (o *ListProfiles200ResponseDataInnerAsset) GetType() Enum7c5a8d597678316a20092b786fdbb3dd {
	if o == nil {
		var ret Enum7c5a8d597678316a20092b786fdbb3dd
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetTypeOk() (*Enum7c5a8d597678316a20092b786fdbb3dd, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetType(v Enum7c5a8d597678316a20092b786fdbb3dd) {
	o.Type = v
}

// GetUri returns the Uri field value
func (o *ListProfiles200ResponseDataInnerAsset) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetUri(v string) {
	o.Uri = v
}

// GetName returns the Name field value
func (o *ListProfiles200ResponseDataInnerAsset) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetName(v string) {
	o.Name = v
}

// GetExternalUrl returns the ExternalUrl field value
func (o *ListProfiles200ResponseDataInnerAsset) GetExternalUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalUrl
}

// GetExternalUrlOk returns a tuple with the ExternalUrl field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetExternalUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalUrl, true
}

// SetExternalUrl sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetExternalUrl(v string) {
	o.ExternalUrl = v
}

// GetFaviconUrl returns the FaviconUrl field value
func (o *ListProfiles200ResponseDataInnerAsset) GetFaviconUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FaviconUrl
}

// GetFaviconUrlOk returns a tuple with the FaviconUrl field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetFaviconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaviconUrl, true
}

// SetFaviconUrl sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetFaviconUrl(v string) {
	o.FaviconUrl = v
}

// GetDescription returns the Description field value
func (o *ListProfiles200ResponseDataInnerAsset) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetDescription(v string) {
	o.Description = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListProfiles200ResponseDataInnerAsset) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetLastSeenAt returns the LastSeenAt field value
func (o *ListProfiles200ResponseDataInnerAsset) GetLastSeenAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastSeenAt
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetLastSeenAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeenAt, true
}

// SetLastSeenAt sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetLastSeenAt(v string) {
	o.LastSeenAt = v
}

// GetScheduledForDeletionAt returns the ScheduledForDeletionAt field value
func (o *ListProfiles200ResponseDataInnerAsset) GetScheduledForDeletionAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduledForDeletionAt
}

// GetScheduledForDeletionAtOk returns a tuple with the ScheduledForDeletionAt field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetScheduledForDeletionAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledForDeletionAt, true
}

// SetScheduledForDeletionAt sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetScheduledForDeletionAt(v string) {
	o.ScheduledForDeletionAt = v
}

// GetStatus returns the Status field value
func (o *ListProfiles200ResponseDataInnerAsset) GetStatus() Enum979d32dc69b8f72f50564e75367bcbb5 {
	if o == nil {
		var ret Enum979d32dc69b8f72f50564e75367bcbb5
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetStatusOk() (*Enum979d32dc69b8f72f50564e75367bcbb5, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetStatus(v Enum979d32dc69b8f72f50564e75367bcbb5) {
	o.Status = v
}

// GetTags returns the Tags field value
func (o *ListProfiles200ResponseDataInnerAsset) GetTags() []ListProfiles200ResponseDataInnerAssetTagsInner {
	if o == nil {
		var ret []ListProfiles200ResponseDataInnerAssetTagsInner
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetTagsOk() ([]ListProfiles200ResponseDataInnerAssetTagsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetTags(v []ListProfiles200ResponseDataInnerAssetTagsInner) {
	o.Tags = v
}

// GetRisks returns the Risks field value
func (o *ListProfiles200ResponseDataInnerAsset) GetRisks() []Enum1ea54cdf1f4480ebf83fc671185f5693 {
	if o == nil {
		var ret []Enum1ea54cdf1f4480ebf83fc671185f5693
		return ret
	}

	return o.Risks
}

// GetRisksOk returns a tuple with the Risks field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetRisksOk() ([]Enum1ea54cdf1f4480ebf83fc671185f5693, bool) {
	if o == nil {
		return nil, false
	}
	return o.Risks, true
}

// SetRisks sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetRisks(v []Enum1ea54cdf1f4480ebf83fc671185f5693) {
	o.Risks = v
}

// GetFirstSeenScan returns the FirstSeenScan field value
func (o *ListProfiles200ResponseDataInnerAsset) GetFirstSeenScan() ListProfiles200ResponseDataInnerAssetFirstSeenScan {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetFirstSeenScan
		return ret
	}

	return o.FirstSeenScan
}

// GetFirstSeenScanOk returns a tuple with the FirstSeenScan field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetFirstSeenScanOk() (*ListProfiles200ResponseDataInnerAssetFirstSeenScan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstSeenScan, true
}

// SetFirstSeenScan sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetFirstSeenScan(v ListProfiles200ResponseDataInnerAssetFirstSeenScan) {
	o.FirstSeenScan = v
}

// GetLastSeenScan returns the LastSeenScan field value
func (o *ListProfiles200ResponseDataInnerAsset) GetLastSeenScan() ListProfiles200ResponseDataInnerAssetFirstSeenScan {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetFirstSeenScan
		return ret
	}

	return o.LastSeenScan
}

// GetLastSeenScanOk returns a tuple with the LastSeenScan field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetLastSeenScanOk() (*ListProfiles200ResponseDataInnerAssetFirstSeenScan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeenScan, true
}

// SetLastSeenScan sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetLastSeenScan(v ListProfiles200ResponseDataInnerAssetFirstSeenScan) {
	o.LastSeenScan = v
}

// GetService returns the Service field value
func (o *ListProfiles200ResponseDataInnerAsset) GetService() ListProfiles200ResponseDataInnerAssetService {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetService
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetServiceOk() (*ListProfiles200ResponseDataInnerAssetService, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetService(v ListProfiles200ResponseDataInnerAssetService) {
	o.Service = v
}

// GetFrontend returns the Frontend field value
func (o *ListProfiles200ResponseDataInnerAsset) GetFrontend() ListProfiles200ResponseDataInnerAssetFrontend {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetFrontend
		return ret
	}

	return o.Frontend
}

// GetFrontendOk returns a tuple with the Frontend field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetFrontendOk() (*ListProfiles200ResponseDataInnerAssetFrontend, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frontend, true
}

// SetFrontend sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetFrontend(v ListProfiles200ResponseDataInnerAssetFrontend) {
	o.Frontend = v
}

// GetHost returns the Host field value
func (o *ListProfiles200ResponseDataInnerAsset) GetHost() ListProfiles200ResponseDataInnerAssetHost {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetHost
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetHostOk() (*ListProfiles200ResponseDataInnerAssetHost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetHost(v ListProfiles200ResponseDataInnerAssetHost) {
	o.Host = v
}

// GetLinks returns the Links field value
func (o *ListProfiles200ResponseDataInnerAsset) GetLinks() ListProfiles200ResponseDataInnerAssetLinks {
	if o == nil {
		var ret ListProfiles200ResponseDataInnerAssetLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListProfiles200ResponseDataInnerAsset) GetLinksOk() (*ListProfiles200ResponseDataInnerAssetLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListProfiles200ResponseDataInnerAsset) SetLinks(v ListProfiles200ResponseDataInnerAssetLinks) {
	o.Links = v
}

func (o ListProfiles200ResponseDataInnerAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProfiles200ResponseDataInnerAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["class"] = o.Class
	toSerialize["type"] = o.Type
	toSerialize["uri"] = o.Uri
	toSerialize["name"] = o.Name
	toSerialize["externalUrl"] = o.ExternalUrl
	toSerialize["faviconUrl"] = o.FaviconUrl
	toSerialize["description"] = o.Description
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["lastSeenAt"] = o.LastSeenAt
	toSerialize["scheduledForDeletionAt"] = o.ScheduledForDeletionAt
	toSerialize["status"] = o.Status
	toSerialize["tags"] = o.Tags
	toSerialize["risks"] = o.Risks
	toSerialize["firstSeenScan"] = o.FirstSeenScan
	toSerialize["lastSeenScan"] = o.LastSeenScan
	toSerialize["service"] = o.Service
	toSerialize["frontend"] = o.Frontend
	toSerialize["host"] = o.Host
	toSerialize["links"] = o.Links

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListProfiles200ResponseDataInnerAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"class",
		"type",
		"uri",
		"name",
		"externalUrl",
		"faviconUrl",
		"description",
		"createdAt",
		"lastSeenAt",
		"scheduledForDeletionAt",
		"status",
		"tags",
		"risks",
		"firstSeenScan",
		"lastSeenScan",
		"service",
		"frontend",
		"host",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListProfiles200ResponseDataInnerAsset := _ListProfiles200ResponseDataInnerAsset{}

	err = json.Unmarshal(data, &varListProfiles200ResponseDataInnerAsset)

	if err != nil {
		return err
	}

	*o = ListProfiles200ResponseDataInnerAsset(varListProfiles200ResponseDataInnerAsset)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "class")
		delete(additionalProperties, "type")
		delete(additionalProperties, "uri")
		delete(additionalProperties, "name")
		delete(additionalProperties, "externalUrl")
		delete(additionalProperties, "faviconUrl")
		delete(additionalProperties, "description")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "lastSeenAt")
		delete(additionalProperties, "scheduledForDeletionAt")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "risks")
		delete(additionalProperties, "firstSeenScan")
		delete(additionalProperties, "lastSeenScan")
		delete(additionalProperties, "service")
		delete(additionalProperties, "frontend")
		delete(additionalProperties, "host")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListProfiles200ResponseDataInnerAsset struct {
	value *ListProfiles200ResponseDataInnerAsset
	isSet bool
}

func (v NullableListProfiles200ResponseDataInnerAsset) Get() *ListProfiles200ResponseDataInnerAsset {
	return v.value
}

func (v *NullableListProfiles200ResponseDataInnerAsset) Set(val *ListProfiles200ResponseDataInnerAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableListProfiles200ResponseDataInnerAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableListProfiles200ResponseDataInnerAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProfiles200ResponseDataInnerAsset(val *ListProfiles200ResponseDataInnerAsset) *NullableListProfiles200ResponseDataInnerAsset {
	return &NullableListProfiles200ResponseDataInnerAsset{value: val, isSet: true}
}

func (v NullableListProfiles200ResponseDataInnerAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProfiles200ResponseDataInnerAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


