/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the ListRegressionTests200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRegressionTests200Response{}

// ListRegressionTests200Response struct for ListRegressionTests200Response
type ListRegressionTests200Response struct {
	NextCursor           *string                 `json:"nextCursor,omitempty"`
	TotalCount           *int                    `json:"totalCount,omitempty"`
	Data                 []RegressionTestSummary `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ListRegressionTests200Response ListRegressionTests200Response

// NewListRegressionTests200Response instantiates a new ListRegressionTests200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRegressionTests200Response(data []RegressionTestSummary) *ListRegressionTests200Response {
	this := ListRegressionTests200Response{}
	var totalCount int = 100
	this.TotalCount = &totalCount
	this.Data = data
	return &this
}

// NewListRegressionTests200ResponseWithDefaults instantiates a new ListRegressionTests200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRegressionTests200ResponseWithDefaults() *ListRegressionTests200Response {
	this := ListRegressionTests200Response{}
	var totalCount int = 100
	this.TotalCount = &totalCount
	return &this
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *ListRegressionTests200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegressionTests200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ListRegressionTests200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *ListRegressionTests200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *ListRegressionTests200Response) GetTotalCount() int {
	if o == nil || IsNil(o.TotalCount) {
		var ret int
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegressionTests200Response) GetTotalCountOk() (*int, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *ListRegressionTests200Response) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int and assigns it to the TotalCount field.
func (o *ListRegressionTests200Response) SetTotalCount(v int) {
	o.TotalCount = &v
}

// GetData returns the Data field value
func (o *ListRegressionTests200Response) GetData() []RegressionTestSummary {
	if o == nil {
		var ret []RegressionTestSummary
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListRegressionTests200Response) GetDataOk() ([]RegressionTestSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListRegressionTests200Response) SetData(v []RegressionTestSummary) {
	o.Data = v
}

func (o ListRegressionTests200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRegressionTests200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListRegressionTests200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListRegressionTests200Response := _ListRegressionTests200Response{}

	err = json.Unmarshal(data, &varListRegressionTests200Response)

	if err != nil {
		return err
	}

	*o = ListRegressionTests200Response(varListRegressionTests200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nextCursor")
		delete(additionalProperties, "totalCount")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListRegressionTests200Response struct {
	value *ListRegressionTests200Response
	isSet bool
}

func (v NullableListRegressionTests200Response) Get() *ListRegressionTests200Response {
	return v.value
}

func (v *NullableListRegressionTests200Response) Set(val *ListRegressionTests200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListRegressionTests200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListRegressionTests200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRegressionTests200Response(val *ListRegressionTests200Response) *NullableListRegressionTests200Response {
	return &NullableListRegressionTests200Response{value: val, isSet: true}
}

func (v NullableListRegressionTests200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRegressionTests200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
