/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEnabledCompliances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEnabledCompliances200Response{}

// GetEnabledCompliances200Response struct for GetEnabledCompliances200Response
type GetEnabledCompliances200Response struct {
	// Enabled compliance frameworks
	Data                 []ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _GetEnabledCompliances200Response GetEnabledCompliances200Response

// NewGetEnabledCompliances200Response instantiates a new GetEnabledCompliances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnabledCompliances200Response(data []ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE) *GetEnabledCompliances200Response {
	this := GetEnabledCompliances200Response{}
	this.Data = data
	return &this
}

// NewGetEnabledCompliances200ResponseWithDefaults instantiates a new GetEnabledCompliances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnabledCompliances200ResponseWithDefaults() *GetEnabledCompliances200Response {
	this := GetEnabledCompliances200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetEnabledCompliances200Response) GetData() []ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE {
	if o == nil {
		var ret []ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetEnabledCompliances200Response) GetDataOk() ([]ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetEnabledCompliances200Response) SetData(v []ENUMPROPERTIESISSUEPROPERTIESCOMPLIANCEITEMSPROPERTIESCOMPLIANCE) {
	o.Data = v
}

func (o GetEnabledCompliances200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEnabledCompliances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEnabledCompliances200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEnabledCompliances200Response := _GetEnabledCompliances200Response{}

	err = json.Unmarshal(data, &varGetEnabledCompliances200Response)

	if err != nil {
		return err
	}

	*o = GetEnabledCompliances200Response(varGetEnabledCompliances200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEnabledCompliances200Response struct {
	value *GetEnabledCompliances200Response
	isSet bool
}

func (v NullableGetEnabledCompliances200Response) Get() *GetEnabledCompliances200Response {
	return v.value
}

func (v *NullableGetEnabledCompliances200Response) Set(val *GetEnabledCompliances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnabledCompliances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnabledCompliances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnabledCompliances200Response(val *GetEnabledCompliances200Response) *NullableGetEnabledCompliances200Response {
	return &NullableGetEnabledCompliances200Response{value: val, isSet: true}
}

func (v NullableGetEnabledCompliances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnabledCompliances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
