/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
)

// checks if the GetProfile200ResponseConfigurationSubdomainEnumeration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProfile200ResponseConfigurationSubdomainEnumeration{}

// GetProfile200ResponseConfigurationSubdomainEnumeration struct for GetProfile200ResponseConfigurationSubdomainEnumeration
type GetProfile200ResponseConfigurationSubdomainEnumeration struct {
	Blocklist            []GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner `json:"blocklist,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetProfile200ResponseConfigurationSubdomainEnumeration GetProfile200ResponseConfigurationSubdomainEnumeration

// NewGetProfile200ResponseConfigurationSubdomainEnumeration instantiates a new GetProfile200ResponseConfigurationSubdomainEnumeration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProfile200ResponseConfigurationSubdomainEnumeration() *GetProfile200ResponseConfigurationSubdomainEnumeration {
	this := GetProfile200ResponseConfigurationSubdomainEnumeration{}
	return &this
}

// NewGetProfile200ResponseConfigurationSubdomainEnumerationWithDefaults instantiates a new GetProfile200ResponseConfigurationSubdomainEnumeration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProfile200ResponseConfigurationSubdomainEnumerationWithDefaults() *GetProfile200ResponseConfigurationSubdomainEnumeration {
	this := GetProfile200ResponseConfigurationSubdomainEnumeration{}
	return &this
}

// GetBlocklist returns the Blocklist field value if set, zero value otherwise.
func (o *GetProfile200ResponseConfigurationSubdomainEnumeration) GetBlocklist() []GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner {
	if o == nil || IsNil(o.Blocklist) {
		var ret []GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner
		return ret
	}
	return o.Blocklist
}

// GetBlocklistOk returns a tuple with the Blocklist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProfile200ResponseConfigurationSubdomainEnumeration) GetBlocklistOk() ([]GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner, bool) {
	if o == nil || IsNil(o.Blocklist) {
		return nil, false
	}
	return o.Blocklist, true
}

// HasBlocklist returns a boolean if a field has been set.
func (o *GetProfile200ResponseConfigurationSubdomainEnumeration) HasBlocklist() bool {
	if o != nil && !IsNil(o.Blocklist) {
		return true
	}

	return false
}

// SetBlocklist gets a reference to the given []GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner and assigns it to the Blocklist field.
func (o *GetProfile200ResponseConfigurationSubdomainEnumeration) SetBlocklist(v []GetProfile200ResponseConfigurationSubdomainEnumerationBlocklistInner) {
	o.Blocklist = v
}

func (o GetProfile200ResponseConfigurationSubdomainEnumeration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProfile200ResponseConfigurationSubdomainEnumeration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Blocklist) {
		toSerialize["blocklist"] = o.Blocklist
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProfile200ResponseConfigurationSubdomainEnumeration) UnmarshalJSON(data []byte) (err error) {
	varGetProfile200ResponseConfigurationSubdomainEnumeration := _GetProfile200ResponseConfigurationSubdomainEnumeration{}

	err = json.Unmarshal(data, &varGetProfile200ResponseConfigurationSubdomainEnumeration)

	if err != nil {
		return err
	}

	*o = GetProfile200ResponseConfigurationSubdomainEnumeration(varGetProfile200ResponseConfigurationSubdomainEnumeration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "blocklist")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProfile200ResponseConfigurationSubdomainEnumeration struct {
	value *GetProfile200ResponseConfigurationSubdomainEnumeration
	isSet bool
}

func (v NullableGetProfile200ResponseConfigurationSubdomainEnumeration) Get() *GetProfile200ResponseConfigurationSubdomainEnumeration {
	return v.value
}

func (v *NullableGetProfile200ResponseConfigurationSubdomainEnumeration) Set(val *GetProfile200ResponseConfigurationSubdomainEnumeration) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProfile200ResponseConfigurationSubdomainEnumeration) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProfile200ResponseConfigurationSubdomainEnumeration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProfile200ResponseConfigurationSubdomainEnumeration(val *GetProfile200ResponseConfigurationSubdomainEnumeration) *NullableGetProfile200ResponseConfigurationSubdomainEnumeration {
	return &NullableGetProfile200ResponseConfigurationSubdomainEnumeration{value: val, isSet: true}
}

func (v NullableGetProfile200ResponseConfigurationSubdomainEnumeration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProfile200ResponseConfigurationSubdomainEnumeration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
