/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
)

// checks if the UpdateakamaiIntegrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateakamaiIntegrationRequest{}

// UpdateakamaiIntegrationRequest struct for UpdateakamaiIntegrationRequest
type UpdateakamaiIntegrationRequest struct {
	// The new name of the integration
	Name *string `json:"name,omitempty"`
	Parameters *UpdateakamaiIntegrationRequestParameters `json:"parameters,omitempty"`
	// Optional proxy ID to attach to the integration
	ProxyId *string `json:"proxyId,omitempty"`
	// Optional list of project IDs to attach to the integration
	ProjectIds []string `json:"projectIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateakamaiIntegrationRequest UpdateakamaiIntegrationRequest

// NewUpdateakamaiIntegrationRequest instantiates a new UpdateakamaiIntegrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateakamaiIntegrationRequest() *UpdateakamaiIntegrationRequest {
	this := UpdateakamaiIntegrationRequest{}
	return &this
}

// NewUpdateakamaiIntegrationRequestWithDefaults instantiates a new UpdateakamaiIntegrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateakamaiIntegrationRequestWithDefaults() *UpdateakamaiIntegrationRequest {
	this := UpdateakamaiIntegrationRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateakamaiIntegrationRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateakamaiIntegrationRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateakamaiIntegrationRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateakamaiIntegrationRequest) SetName(v string) {
	o.Name = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *UpdateakamaiIntegrationRequest) GetParameters() UpdateakamaiIntegrationRequestParameters {
	if o == nil || IsNil(o.Parameters) {
		var ret UpdateakamaiIntegrationRequestParameters
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateakamaiIntegrationRequest) GetParametersOk() (*UpdateakamaiIntegrationRequestParameters, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *UpdateakamaiIntegrationRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given UpdateakamaiIntegrationRequestParameters and assigns it to the Parameters field.
func (o *UpdateakamaiIntegrationRequest) SetParameters(v UpdateakamaiIntegrationRequestParameters) {
	o.Parameters = &v
}

// GetProxyId returns the ProxyId field value if set, zero value otherwise.
func (o *UpdateakamaiIntegrationRequest) GetProxyId() string {
	if o == nil || IsNil(o.ProxyId) {
		var ret string
		return ret
	}
	return *o.ProxyId
}

// GetProxyIdOk returns a tuple with the ProxyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateakamaiIntegrationRequest) GetProxyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyId) {
		return nil, false
	}
	return o.ProxyId, true
}

// HasProxyId returns a boolean if a field has been set.
func (o *UpdateakamaiIntegrationRequest) HasProxyId() bool {
	if o != nil && !IsNil(o.ProxyId) {
		return true
	}

	return false
}

// SetProxyId gets a reference to the given string and assigns it to the ProxyId field.
func (o *UpdateakamaiIntegrationRequest) SetProxyId(v string) {
	o.ProxyId = &v
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise.
func (o *UpdateakamaiIntegrationRequest) GetProjectIds() []string {
	if o == nil || IsNil(o.ProjectIds) {
		var ret []string
		return ret
	}
	return o.ProjectIds
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateakamaiIntegrationRequest) GetProjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectIds) {
		return nil, false
	}
	return o.ProjectIds, true
}

// HasProjectIds returns a boolean if a field has been set.
func (o *UpdateakamaiIntegrationRequest) HasProjectIds() bool {
	if o != nil && !IsNil(o.ProjectIds) {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given []string and assigns it to the ProjectIds field.
func (o *UpdateakamaiIntegrationRequest) SetProjectIds(v []string) {
	o.ProjectIds = v
}

func (o UpdateakamaiIntegrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateakamaiIntegrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.ProxyId) {
		toSerialize["proxyId"] = o.ProxyId
	}
	if !IsNil(o.ProjectIds) {
		toSerialize["projectIds"] = o.ProjectIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateakamaiIntegrationRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateakamaiIntegrationRequest := _UpdateakamaiIntegrationRequest{}

	err = json.Unmarshal(data, &varUpdateakamaiIntegrationRequest)

	if err != nil {
		return err
	}

	*o = UpdateakamaiIntegrationRequest(varUpdateakamaiIntegrationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "proxyId")
		delete(additionalProperties, "projectIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateakamaiIntegrationRequest struct {
	value *UpdateakamaiIntegrationRequest
	isSet bool
}

func (v NullableUpdateakamaiIntegrationRequest) Get() *UpdateakamaiIntegrationRequest {
	return v.value
}

func (v *NullableUpdateakamaiIntegrationRequest) Set(val *UpdateakamaiIntegrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateakamaiIntegrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateakamaiIntegrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateakamaiIntegrationRequest(val *UpdateakamaiIntegrationRequest) *NullableUpdateakamaiIntegrationRequest {
	return &NullableUpdateakamaiIntegrationRequest{value: val, isSet: true}
}

func (v NullableUpdateakamaiIntegrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateakamaiIntegrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


