/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner{}

// ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner struct for ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner
type ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner struct {
	Username string `json:"username"`
	Headers map[string]string `json:"headers,omitempty"`
	Cookies map[string]string `json:"cookies,omitempty"`
	QueryParameters map[string]string `json:"query_parameters,omitempty"`
	Variables map[string]string `json:"variables"`
	AdditionalProperties map[string]interface{}
}

type _ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner

// NewProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner instantiates a new ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner(username string, variables map[string]string) *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner {
	this := ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner{}
	this.Username = username
	this.Variables = variables
	return &this
}

// NewProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInnerWithDefaults instantiates a new ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInnerWithDefaults() *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner {
	this := ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner{}
	return &this
}

// GetUsername returns the Username field value
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) SetUsername(v string) {
	o.Username = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetHeadersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetCookies returns the Cookies field value if set, zero value otherwise.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetCookies() map[string]string {
	if o == nil || IsNil(o.Cookies) {
		var ret map[string]string
		return ret
	}
	return o.Cookies
}

// GetCookiesOk returns a tuple with the Cookies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetCookiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Cookies) {
		return map[string]string{}, false
	}
	return o.Cookies, true
}

// HasCookies returns a boolean if a field has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) HasCookies() bool {
	if o != nil && !IsNil(o.Cookies) {
		return true
	}

	return false
}

// SetCookies gets a reference to the given map[string]string and assigns it to the Cookies field.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) SetCookies(v map[string]string) {
	o.Cookies = v
}

// GetQueryParameters returns the QueryParameters field value if set, zero value otherwise.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetQueryParameters() map[string]string {
	if o == nil || IsNil(o.QueryParameters) {
		var ret map[string]string
		return ret
	}
	return o.QueryParameters
}

// GetQueryParametersOk returns a tuple with the QueryParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetQueryParametersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.QueryParameters) {
		return map[string]string{}, false
	}
	return o.QueryParameters, true
}

// HasQueryParameters returns a boolean if a field has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) HasQueryParameters() bool {
	if o != nil && !IsNil(o.QueryParameters) {
		return true
	}

	return false
}

// SetQueryParameters gets a reference to the given map[string]string and assigns it to the QueryParameters field.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) SetQueryParameters(v map[string]string) {
	o.QueryParameters = v
}

// GetVariables returns the Variables field value
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetVariables() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) GetVariablesOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Variables, true
}

// SetVariables sets field value
func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) SetVariables(v map[string]string) {
	o.Variables = v
}

func (o ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Cookies) {
		toSerialize["cookies"] = o.Cookies
	}
	if !IsNil(o.QueryParameters) {
		toSerialize["query_parameters"] = o.QueryParameters
	}
	toSerialize["variables"] = o.Variables

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"variables",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner := _ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner{}

	err = json.Unmarshal(data, &varProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner)

	if err != nil {
		return err
	}

	*o = ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner(varProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "cookies")
		delete(additionalProperties, "query_parameters")
		delete(additionalProperties, "variables")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner struct {
	value *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner
	isSet bool
}

func (v NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) Get() *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner {
	return v.value
}

func (v *NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) Set(val *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner(val *ProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) *NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner {
	return &NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner{value: val, isSet: true}
}

func (v NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileDetailedConfigurationAuthenticationPresetsInnerOneOf5UsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


