/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateAssetParentLinksSetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAssetParentLinksSetInner{}

// UpdateAssetParentLinksSetInner struct for UpdateAssetParentLinksSetInner
type UpdateAssetParentLinksSetInner struct {
	// The ID of the asset the link points to
	TargetId             string                                                    `json:"targetId"`
	Verb                 ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB `json:"verb"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAssetParentLinksSetInner UpdateAssetParentLinksSetInner

// NewUpdateAssetParentLinksSetInner instantiates a new UpdateAssetParentLinksSetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAssetParentLinksSetInner(targetId string, verb ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB) *UpdateAssetParentLinksSetInner {
	this := UpdateAssetParentLinksSetInner{}
	this.TargetId = targetId
	this.Verb = verb
	return &this
}

// NewUpdateAssetParentLinksSetInnerWithDefaults instantiates a new UpdateAssetParentLinksSetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAssetParentLinksSetInnerWithDefaults() *UpdateAssetParentLinksSetInner {
	this := UpdateAssetParentLinksSetInner{}
	return &this
}

// GetTargetId returns the TargetId field value
func (o *UpdateAssetParentLinksSetInner) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *UpdateAssetParentLinksSetInner) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *UpdateAssetParentLinksSetInner) SetTargetId(v string) {
	o.TargetId = v
}

// GetVerb returns the Verb field value
func (o *UpdateAssetParentLinksSetInner) GetVerb() ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB {
	if o == nil {
		var ret ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB
		return ret
	}

	return o.Verb
}

// GetVerbOk returns a tuple with the Verb field value
// and a boolean to check if the value has been set.
func (o *UpdateAssetParentLinksSetInner) GetVerbOk() (*ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verb, true
}

// SetVerb sets field value
func (o *UpdateAssetParentLinksSetInner) SetVerb(v ENUMPROPERTIESPARENTLINKSPROPERTIESSETITEMSPROPERTIESVERB) {
	o.Verb = v
}

func (o UpdateAssetParentLinksSetInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAssetParentLinksSetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targetId"] = o.TargetId
	toSerialize["verb"] = o.Verb

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAssetParentLinksSetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targetId",
		"verb",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAssetParentLinksSetInner := _UpdateAssetParentLinksSetInner{}

	err = json.Unmarshal(data, &varUpdateAssetParentLinksSetInner)

	if err != nil {
		return err
	}

	*o = UpdateAssetParentLinksSetInner(varUpdateAssetParentLinksSetInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targetId")
		delete(additionalProperties, "verb")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAssetParentLinksSetInner struct {
	value *UpdateAssetParentLinksSetInner
	isSet bool
}

func (v NullableUpdateAssetParentLinksSetInner) Get() *UpdateAssetParentLinksSetInner {
	return v.value
}

func (v *NullableUpdateAssetParentLinksSetInner) Set(val *UpdateAssetParentLinksSetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAssetParentLinksSetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAssetParentLinksSetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAssetParentLinksSetInner(val *UpdateAssetParentLinksSetInner) *NullableUpdateAssetParentLinksSetInner {
	return &NullableUpdateAssetParentLinksSetInner{value: val, isSet: true}
}

func (v NullableUpdateAssetParentLinksSetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAssetParentLinksSetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
