/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21{}

// CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 struct for CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21
type CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 struct {
	Not interface{} `json:"not,omitempty"`
	If EnumNOT `json:"if"`
	AdditionalProperties map[string]interface{}
}

type _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21(if_ EnumNOT) *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21{}
	this.If = if_
	return &this
}

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21WithDefaults instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21WithDefaults() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21{}
	return &this
}

// GetNot returns the Not field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) GetNot() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Not
}

// GetNotOk returns a tuple with the Not field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) GetNotOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Not) {
		return nil, false
	}
	return &o.Not, true
}

// HasNot returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) HasNot() bool {
	if o != nil && !IsNil(o.Not) {
		return true
	}

	return false
}

// SetNot gets a reference to the given interface{} and assigns it to the Not field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) SetNot(v interface{}) {
	o.Not = v
}

// GetIf returns the If field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) GetIf() EnumNOT {
	if o == nil {
		var ret EnumNOT
		return ret
	}

	return o.If
}

// GetIfOk returns a tuple with the If field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) GetIfOk() (*EnumNOT, bool) {
	if o == nil {
		return nil, false
	}
	return &o.If, true
}

// SetIf sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) SetIf(v EnumNOT) {
	o.If = v
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Not != nil {
		toSerialize["not"] = o.Not
	}
	toSerialize["if"] = o.If

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"if",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 := _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21{}

	err = json.Unmarshal(data, &varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21)

	if err != nil {
		return err
	}

	*o = CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21(varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "not")
		delete(additionalProperties, "if")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 struct {
	value *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21
	isSet bool
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) Get() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 {
	return v.value
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) Set(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21 {
	return &NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21{value: val, isSet: true}
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInnerOneOf21) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


