/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// ListAssetsPortsParameterAnyOfInner struct for ListAssetsPortsParameterAnyOfInner
type ListAssetsPortsParameterAnyOfInner struct {
	Float32 *float32
	String  *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ListAssetsPortsParameterAnyOfInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ListAssetsPortsParameterAnyOfInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ListAssetsPortsParameterAnyOfInner) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableListAssetsPortsParameterAnyOfInner struct {
	value *ListAssetsPortsParameterAnyOfInner
	isSet bool
}

func (v NullableListAssetsPortsParameterAnyOfInner) Get() *ListAssetsPortsParameterAnyOfInner {
	return v.value
}

func (v *NullableListAssetsPortsParameterAnyOfInner) Set(val *ListAssetsPortsParameterAnyOfInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListAssetsPortsParameterAnyOfInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListAssetsPortsParameterAnyOfInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAssetsPortsParameterAnyOfInner(val *ListAssetsPortsParameterAnyOfInner) *NullableListAssetsPortsParameterAnyOfInner {
	return &NullableListAssetsPortsParameterAnyOfInner{value: val, isSet: true}
}

func (v NullableListAssetsPortsParameterAnyOfInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAssetsPortsParameterAnyOfInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
