/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// ENUMOAUTHAUTHZCODEHTTP the model 'ENUMOAUTHAUTHZCODEHTTP'
type ENUMOAUTHAUTHZCODEHTTP string

// List of ENUM_OAUTH_AUTHZ_CODE_HTTP
const (
	ENUMOAUTHAUTHZCODEHTTP_OAUTH_AUTHZ_CODE_HTTP ENUMOAUTHAUTHZCODEHTTP = "oauth_authz_code_http"
)

// All allowed values of ENUMOAUTHAUTHZCODEHTTP enum
var AllowedENUMOAUTHAUTHZCODEHTTPEnumValues = []ENUMOAUTHAUTHZCODEHTTP{
	"oauth_authz_code_http",
}

func (v *ENUMOAUTHAUTHZCODEHTTP) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ENUMOAUTHAUTHZCODEHTTP(value)
	for _, existing := range AllowedENUMOAUTHAUTHZCODEHTTPEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ENUMOAUTHAUTHZCODEHTTP", value)
}

// NewENUMOAUTHAUTHZCODEHTTPFromValue returns a pointer to a valid ENUMOAUTHAUTHZCODEHTTP
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewENUMOAUTHAUTHZCODEHTTPFromValue(v string) (*ENUMOAUTHAUTHZCODEHTTP, error) {
	ev := ENUMOAUTHAUTHZCODEHTTP(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ENUMOAUTHAUTHZCODEHTTP: valid values are %v", v, AllowedENUMOAUTHAUTHZCODEHTTPEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ENUMOAUTHAUTHZCODEHTTP) IsValid() bool {
	for _, existing := range AllowedENUMOAUTHAUTHZCODEHTTPEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ENUM_OAUTH_AUTHZ_CODE_HTTP value
func (v ENUMOAUTHAUTHZCODEHTTP) Ptr() *ENUMOAUTHAUTHZCODEHTTP {
	return &v
}

type NullableENUMOAUTHAUTHZCODEHTTP struct {
	value *ENUMOAUTHAUTHZCODEHTTP
	isSet bool
}

func (v NullableENUMOAUTHAUTHZCODEHTTP) Get() *ENUMOAUTHAUTHZCODEHTTP {
	return v.value
}

func (v *NullableENUMOAUTHAUTHZCODEHTTP) Set(val *ENUMOAUTHAUTHZCODEHTTP) {
	v.value = val
	v.isSet = true
}

func (v NullableENUMOAUTHAUTHZCODEHTTP) IsSet() bool {
	return v.isSet
}

func (v *NullableENUMOAUTHAUTHZCODEHTTP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableENUMOAUTHAUTHZCODEHTTP(val *ENUMOAUTHAUTHZCODEHTTP) *NullableENUMOAUTHAUTHZCODEHTTP {
	return &NullableENUMOAUTHAUTHZCODEHTTP{value: val, isSet: true}
}

func (v NullableENUMOAUTHAUTHZCODEHTTP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableENUMOAUTHAUTHZCODEHTTP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

