/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf{}

// ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf struct for ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf
type ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf struct {
	Action ENUMCLICK `json:"action"`
	AllowFailure *bool `json:"allow_failure,omitempty"`
	Locator string `json:"locator"`
	Timeout *float32 `json:"timeout,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf

// NewProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf instantiates a new ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf(action ENUMCLICK, locator string) *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf {
	this := ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf{}
	this.Action = action
	this.Locator = locator
	return &this
}

// NewProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOfWithDefaults instantiates a new ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOfWithDefaults() *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf {
	this := ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf{}
	return &this
}

// GetAction returns the Action field value
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetAction() ENUMCLICK {
	if o == nil {
		var ret ENUMCLICK
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetActionOk() (*ENUMCLICK, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) SetAction(v ENUMCLICK) {
	o.Action = v
}

// GetAllowFailure returns the AllowFailure field value if set, zero value otherwise.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetAllowFailure() bool {
	if o == nil || IsNil(o.AllowFailure) {
		var ret bool
		return ret
	}
	return *o.AllowFailure
}

// GetAllowFailureOk returns a tuple with the AllowFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetAllowFailureOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowFailure) {
		return nil, false
	}
	return o.AllowFailure, true
}

// HasAllowFailure returns a boolean if a field has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) HasAllowFailure() bool {
	if o != nil && !IsNil(o.AllowFailure) {
		return true
	}

	return false
}

// SetAllowFailure gets a reference to the given bool and assigns it to the AllowFailure field.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) SetAllowFailure(v bool) {
	o.AllowFailure = &v
}

// GetLocator returns the Locator field value
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetLocator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locator
}

// GetLocatorOk returns a tuple with the Locator field value
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetLocatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locator, true
}

// SetLocator sets field value
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) SetLocator(v string) {
	o.Locator = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetTimeout() float32 {
	if o == nil || IsNil(o.Timeout) {
		var ret float32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) GetTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given float32 and assigns it to the Timeout field.
func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) SetTimeout(v float32) {
	o.Timeout = &v
}

func (o ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.AllowFailure) {
		toSerialize["allow_failure"] = o.AllowFailure
	}
	toSerialize["locator"] = o.Locator
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"locator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf := _ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf{}

	err = json.Unmarshal(data, &varProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf)

	if err != nil {
		return err
	}

	*o = ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf(varProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "allow_failure")
		delete(additionalProperties, "locator")
		delete(additionalProperties, "timeout")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf struct {
	value *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf
	isSet bool
}

func (v NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) Get() *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf {
	return v.value
}

func (v *NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) Set(val *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf(val *ProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) *NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf {
	return &NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf{value: val, isSet: true}
}

func (v NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileDetailedConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


