/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)


// UpdateIssueRequestSeverity The issue severity
type UpdateIssueRequestSeverity struct {
	ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY *ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY
	UpdateIssueRequestSeverityAnyOf *UpdateIssueRequestSeverityAnyOf
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpdateIssueRequestSeverity) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY
	err = json.Unmarshal(data, &dst.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY);
	if err == nil {
		jsonENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY, _ := json.Marshal(dst.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY)
		if string(jsonENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY) == "{}" { // empty struct
			dst.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY = nil
		} else {
			return nil // data stored in dst.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY, return on the first match
		}
	} else {
		dst.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY = nil
	}

	// try to unmarshal JSON data into UpdateIssueRequestSeverityAnyOf
	err = json.Unmarshal(data, &dst.UpdateIssueRequestSeverityAnyOf);
	if err == nil {
		jsonUpdateIssueRequestSeverityAnyOf, _ := json.Marshal(dst.UpdateIssueRequestSeverityAnyOf)
		if string(jsonUpdateIssueRequestSeverityAnyOf) == "{}" { // empty struct
			dst.UpdateIssueRequestSeverityAnyOf = nil
		} else {
			return nil // data stored in dst.UpdateIssueRequestSeverityAnyOf, return on the first match
		}
	} else {
		dst.UpdateIssueRequestSeverityAnyOf = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UpdateIssueRequestSeverity)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateIssueRequestSeverity) MarshalJSON() ([]byte, error) {
	if src.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY != nil {
		return json.Marshal(&src.ENUMPROPERTIESDATAITEMSPROPERTIESSEVERITY)
	}

	if src.UpdateIssueRequestSeverityAnyOf != nil {
		return json.Marshal(&src.UpdateIssueRequestSeverityAnyOf)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableUpdateIssueRequestSeverity struct {
	value *UpdateIssueRequestSeverity
	isSet bool
}

func (v NullableUpdateIssueRequestSeverity) Get() *UpdateIssueRequestSeverity {
	return v.value
}

func (v *NullableUpdateIssueRequestSeverity) Set(val *UpdateIssueRequestSeverity) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateIssueRequestSeverity) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateIssueRequestSeverity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateIssueRequestSeverity(val *UpdateIssueRequestSeverity) *NullableUpdateIssueRequestSeverity {
	return &NullableUpdateIssueRequestSeverity{value: val, isSet: true}
}

func (v NullableUpdateIssueRequestSeverity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateIssueRequestSeverity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


