/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateawsIntegrationRequestParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateawsIntegrationRequestParameters{}

// CreateawsIntegrationRequestParameters The parameters of the integration
type CreateawsIntegrationRequestParameters struct {
	PublicKey string `json:"public_key"`
	PrivateKey string `json:"private_key"`
	ExternalIntegrationRoleArn *string `json:"external_integration_role_arn,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateawsIntegrationRequestParameters CreateawsIntegrationRequestParameters

// NewCreateawsIntegrationRequestParameters instantiates a new CreateawsIntegrationRequestParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateawsIntegrationRequestParameters(publicKey string, privateKey string) *CreateawsIntegrationRequestParameters {
	this := CreateawsIntegrationRequestParameters{}
	this.PublicKey = publicKey
	this.PrivateKey = privateKey
	return &this
}

// NewCreateawsIntegrationRequestParametersWithDefaults instantiates a new CreateawsIntegrationRequestParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateawsIntegrationRequestParametersWithDefaults() *CreateawsIntegrationRequestParameters {
	this := CreateawsIntegrationRequestParameters{}
	return &this
}

// GetPublicKey returns the PublicKey field value
func (o *CreateawsIntegrationRequestParameters) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *CreateawsIntegrationRequestParameters) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *CreateawsIntegrationRequestParameters) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetPrivateKey returns the PrivateKey field value
func (o *CreateawsIntegrationRequestParameters) GetPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value
// and a boolean to check if the value has been set.
func (o *CreateawsIntegrationRequestParameters) GetPrivateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateKey, true
}

// SetPrivateKey sets field value
func (o *CreateawsIntegrationRequestParameters) SetPrivateKey(v string) {
	o.PrivateKey = v
}

// GetExternalIntegrationRoleArn returns the ExternalIntegrationRoleArn field value if set, zero value otherwise.
func (o *CreateawsIntegrationRequestParameters) GetExternalIntegrationRoleArn() string {
	if o == nil || IsNil(o.ExternalIntegrationRoleArn) {
		var ret string
		return ret
	}
	return *o.ExternalIntegrationRoleArn
}

// GetExternalIntegrationRoleArnOk returns a tuple with the ExternalIntegrationRoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateawsIntegrationRequestParameters) GetExternalIntegrationRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalIntegrationRoleArn) {
		return nil, false
	}
	return o.ExternalIntegrationRoleArn, true
}

// HasExternalIntegrationRoleArn returns a boolean if a field has been set.
func (o *CreateawsIntegrationRequestParameters) HasExternalIntegrationRoleArn() bool {
	if o != nil && !IsNil(o.ExternalIntegrationRoleArn) {
		return true
	}

	return false
}

// SetExternalIntegrationRoleArn gets a reference to the given string and assigns it to the ExternalIntegrationRoleArn field.
func (o *CreateawsIntegrationRequestParameters) SetExternalIntegrationRoleArn(v string) {
	o.ExternalIntegrationRoleArn = &v
}

func (o CreateawsIntegrationRequestParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateawsIntegrationRequestParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_key"] = o.PublicKey
	toSerialize["private_key"] = o.PrivateKey
	if !IsNil(o.ExternalIntegrationRoleArn) {
		toSerialize["external_integration_role_arn"] = o.ExternalIntegrationRoleArn
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateawsIntegrationRequestParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_key",
		"private_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateawsIntegrationRequestParameters := _CreateawsIntegrationRequestParameters{}

	err = json.Unmarshal(data, &varCreateawsIntegrationRequestParameters)

	if err != nil {
		return err
	}

	*o = CreateawsIntegrationRequestParameters(varCreateawsIntegrationRequestParameters)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "public_key")
		delete(additionalProperties, "private_key")
		delete(additionalProperties, "external_integration_role_arn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateawsIntegrationRequestParameters struct {
	value *CreateawsIntegrationRequestParameters
	isSet bool
}

func (v NullableCreateawsIntegrationRequestParameters) Get() *CreateawsIntegrationRequestParameters {
	return v.value
}

func (v *NullableCreateawsIntegrationRequestParameters) Set(val *CreateawsIntegrationRequestParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateawsIntegrationRequestParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateawsIntegrationRequestParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateawsIntegrationRequestParameters(val *CreateawsIntegrationRequestParameters) *NullableCreateawsIntegrationRequestParameters {
	return &NullableCreateawsIntegrationRequestParameters{value: val, isSet: true}
}

func (v NullableCreateawsIntegrationRequestParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateawsIntegrationRequestParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


