/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner - struct for ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
type ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner struct {
	ProfileDetailedConfigurationScopeAllowlistInnerOneOf *ProfileDetailedConfigurationScopeAllowlistInnerOneOf
	ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 *ProfileDetailedConfigurationScopeAllowlistInnerOneOf1
	ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 *ProfileDetailedConfigurationScopeAllowlistInnerOneOf3
	ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 *ProfileDetailedConfigurationScopeAllowlistInnerOneOf4
	ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 *ProfileDetailedConfigurationScopeAllowlistInnerOneOf5
}

// ProfileDetailedConfigurationScopeAllowlistInnerOneOfAsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner is a convenience function that returns ProfileDetailedConfigurationScopeAllowlistInnerOneOf wrapped in ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
func ProfileDetailedConfigurationScopeAllowlistInnerOneOfAsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(v *ProfileDetailedConfigurationScopeAllowlistInnerOneOf) ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{
		ProfileDetailedConfigurationScopeAllowlistInnerOneOf: v,
	}
}

// ProfileDetailedConfigurationScopeAllowlistInnerOneOf1AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner is a convenience function that returns ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 wrapped in ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
func ProfileDetailedConfigurationScopeAllowlistInnerOneOf1AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(v *ProfileDetailedConfigurationScopeAllowlistInnerOneOf1) ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{
		ProfileDetailedConfigurationScopeAllowlistInnerOneOf1: v,
	}
}

// ProfileDetailedConfigurationScopeAllowlistInnerOneOf3AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner is a convenience function that returns ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 wrapped in ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
func ProfileDetailedConfigurationScopeAllowlistInnerOneOf3AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(v *ProfileDetailedConfigurationScopeAllowlistInnerOneOf3) ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{
		ProfileDetailedConfigurationScopeAllowlistInnerOneOf3: v,
	}
}

// ProfileDetailedConfigurationScopeAllowlistInnerOneOf4AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner is a convenience function that returns ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 wrapped in ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
func ProfileDetailedConfigurationScopeAllowlistInnerOneOf4AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(v *ProfileDetailedConfigurationScopeAllowlistInnerOneOf4) ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{
		ProfileDetailedConfigurationScopeAllowlistInnerOneOf4: v,
	}
}

// ProfileDetailedConfigurationScopeAllowlistInnerOneOf5AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner is a convenience function that returns ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 wrapped in ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
func ProfileDetailedConfigurationScopeAllowlistInnerOneOf5AsProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(v *ProfileDetailedConfigurationScopeAllowlistInnerOneOf5) ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{
		ProfileDetailedConfigurationScopeAllowlistInnerOneOf5: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ProfileDetailedConfigurationScopeAllowlistInnerOneOf
	err = newStrictDecoder(data).Decode(&dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf)
	if err == nil {
		jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf, _ := json.Marshal(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf)
		if string(jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf) == "{}" { // empty struct
			dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf = nil
		} else {
			if err = validator.Validate(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf); err != nil {
				dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf = nil
	}

	// try to unmarshal data into ProfileDetailedConfigurationScopeAllowlistInnerOneOf1
	err = newStrictDecoder(data).Decode(&dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1)
	if err == nil {
		jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf1, _ := json.Marshal(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1)
		if string(jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf1) == "{}" { // empty struct
			dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1); err != nil {
				dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 = nil
	}

	// try to unmarshal data into ProfileDetailedConfigurationScopeAllowlistInnerOneOf3
	err = newStrictDecoder(data).Decode(&dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3)
	if err == nil {
		jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf3, _ := json.Marshal(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3)
		if string(jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf3) == "{}" { // empty struct
			dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3); err != nil {
				dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 = nil
	}

	// try to unmarshal data into ProfileDetailedConfigurationScopeAllowlistInnerOneOf4
	err = newStrictDecoder(data).Decode(&dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4)
	if err == nil {
		jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf4, _ := json.Marshal(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4)
		if string(jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf4) == "{}" { // empty struct
			dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 = nil
		} else {
			if err = validator.Validate(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4); err != nil {
				dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 = nil
	}

	// try to unmarshal data into ProfileDetailedConfigurationScopeAllowlistInnerOneOf5
	err = newStrictDecoder(data).Decode(&dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5)
	if err == nil {
		jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf5, _ := json.Marshal(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5)
		if string(jsonProfileDetailedConfigurationScopeAllowlistInnerOneOf5) == "{}" { // empty struct
			dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 = nil
		} else {
			if err = validator.Validate(dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5); err != nil {
				dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf = nil
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 = nil
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 = nil
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 = nil
		dst.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) MarshalJSON() ([]byte, error) {
	if src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf != nil {
		return json.Marshal(&src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf)
	}

	if src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 != nil {
		return json.Marshal(&src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1)
	}

	if src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 != nil {
		return json.Marshal(&src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3)
	}

	if src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 != nil {
		return json.Marshal(&src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4)
	}

	if src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 != nil {
		return json.Marshal(&src.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf != nil {
		return obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 != nil {
		return obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 != nil {
		return obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 != nil {
		return obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 != nil {
		return obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) GetActualInstanceValue() (interface{}) {
	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf != nil {
		return *obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1 != nil {
		return *obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf1
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3 != nil {
		return *obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf3
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4 != nil {
		return *obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf4
	}

	if obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5 != nil {
		return *obj.ProfileDetailedConfigurationScopeAllowlistInnerOneOf5
	}

	// all schemas are nil
	return nil
}

type NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner struct {
	value *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner
	isSet bool
}

func (v NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) Get() *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return v.value
}

func (v *NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) Set(val *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner(val *ProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) *NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner {
	return &NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner{value: val, isSet: true}
}

func (v NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileDetailedConfigurationFrontendDastScopeApiTestingAllowlistInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


