/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
)

// checks if the UpdateAssetParentLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAssetParentLinks{}

// UpdateAssetParentLinks Parent link updates
type UpdateAssetParentLinks struct {
	// Links to set
	Set []UpdateAssetParentLinksSetInner `json:"set,omitempty"`
	// Links to delete
	Delete []UpdateAssetParentLinksSetInner `json:"delete,omitempty"`
	// Links to create
	Create               []UpdateAssetParentLinksSetInner `json:"create,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAssetParentLinks UpdateAssetParentLinks

// NewUpdateAssetParentLinks instantiates a new UpdateAssetParentLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAssetParentLinks() *UpdateAssetParentLinks {
	this := UpdateAssetParentLinks{}
	return &this
}

// NewUpdateAssetParentLinksWithDefaults instantiates a new UpdateAssetParentLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAssetParentLinksWithDefaults() *UpdateAssetParentLinks {
	this := UpdateAssetParentLinks{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *UpdateAssetParentLinks) GetSet() []UpdateAssetParentLinksSetInner {
	if o == nil || IsNil(o.Set) {
		var ret []UpdateAssetParentLinksSetInner
		return ret
	}
	return o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAssetParentLinks) GetSetOk() ([]UpdateAssetParentLinksSetInner, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *UpdateAssetParentLinks) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given []UpdateAssetParentLinksSetInner and assigns it to the Set field.
func (o *UpdateAssetParentLinks) SetSet(v []UpdateAssetParentLinksSetInner) {
	o.Set = v
}

// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *UpdateAssetParentLinks) GetDelete() []UpdateAssetParentLinksSetInner {
	if o == nil || IsNil(o.Delete) {
		var ret []UpdateAssetParentLinksSetInner
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAssetParentLinks) GetDeleteOk() ([]UpdateAssetParentLinksSetInner, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *UpdateAssetParentLinks) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []UpdateAssetParentLinksSetInner and assigns it to the Delete field.
func (o *UpdateAssetParentLinks) SetDelete(v []UpdateAssetParentLinksSetInner) {
	o.Delete = v
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *UpdateAssetParentLinks) GetCreate() []UpdateAssetParentLinksSetInner {
	if o == nil || IsNil(o.Create) {
		var ret []UpdateAssetParentLinksSetInner
		return ret
	}
	return o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAssetParentLinks) GetCreateOk() ([]UpdateAssetParentLinksSetInner, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *UpdateAssetParentLinks) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given []UpdateAssetParentLinksSetInner and assigns it to the Create field.
func (o *UpdateAssetParentLinks) SetCreate(v []UpdateAssetParentLinksSetInner) {
	o.Create = v
}

func (o UpdateAssetParentLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAssetParentLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAssetParentLinks) UnmarshalJSON(data []byte) (err error) {
	varUpdateAssetParentLinks := _UpdateAssetParentLinks{}

	err = json.Unmarshal(data, &varUpdateAssetParentLinks)

	if err != nil {
		return err
	}

	*o = UpdateAssetParentLinks(varUpdateAssetParentLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "set")
		delete(additionalProperties, "delete")
		delete(additionalProperties, "create")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAssetParentLinks struct {
	value *UpdateAssetParentLinks
	isSet bool
}

func (v NullableUpdateAssetParentLinks) Get() *UpdateAssetParentLinks {
	return v.value
}

func (v *NullableUpdateAssetParentLinks) Set(val *UpdateAssetParentLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAssetParentLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAssetParentLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAssetParentLinks(val *UpdateAssetParentLinks) *NullableUpdateAssetParentLinks {
	return &NullableUpdateAssetParentLinks{value: val, isSet: true}
}

func (v NullableUpdateAssetParentLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAssetParentLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
