/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner{}

// CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner struct for CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner
type CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner struct {
	Username string `json:"username"`
	Headers map[string]string `json:"headers,omitempty"`
	Cookies map[string]string `json:"cookies,omitempty"`
	Password *string `json:"password,omitempty"`
	QueryParameters map[string]string `json:"queryParameters,omitempty"`
	Body interface{} `json:"body,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner

// NewCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner instantiates a new CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner(username string) *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner {
	this := CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner{}
	this.Username = username
	return &this
}

// NewCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInnerWithDefaults instantiates a new CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInnerWithDefaults() *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner {
	this := CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner{}
	return &this
}

// GetUsername returns the Username field value
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetUsername(v string) {
	o.Username = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetHeadersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetCookies returns the Cookies field value if set, zero value otherwise.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetCookies() map[string]string {
	if o == nil || IsNil(o.Cookies) {
		var ret map[string]string
		return ret
	}
	return o.Cookies
}

// GetCookiesOk returns a tuple with the Cookies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetCookiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Cookies) {
		return map[string]string{}, false
	}
	return o.Cookies, true
}

// HasCookies returns a boolean if a field has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) HasCookies() bool {
	if o != nil && !IsNil(o.Cookies) {
		return true
	}

	return false
}

// SetCookies gets a reference to the given map[string]string and assigns it to the Cookies field.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetCookies(v map[string]string) {
	o.Cookies = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetPassword(v string) {
	o.Password = &v
}

// GetQueryParameters returns the QueryParameters field value if set, zero value otherwise.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetQueryParameters() map[string]string {
	if o == nil || IsNil(o.QueryParameters) {
		var ret map[string]string
		return ret
	}
	return o.QueryParameters
}

// GetQueryParametersOk returns a tuple with the QueryParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetQueryParametersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.QueryParameters) {
		return map[string]string{}, false
	}
	return o.QueryParameters, true
}

// HasQueryParameters returns a boolean if a field has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) HasQueryParameters() bool {
	if o != nil && !IsNil(o.QueryParameters) {
		return true
	}

	return false
}

// SetQueryParameters gets a reference to the given map[string]string and assigns it to the QueryParameters field.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetQueryParameters(v map[string]string) {
	o.QueryParameters = v
}

// GetBody returns the Body field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given interface{} and assigns it to the Body field.
func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) SetBody(v interface{}) {
	o.Body = v
}

func (o CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Cookies) {
		toSerialize["cookies"] = o.Cookies
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.QueryParameters) {
		toSerialize["queryParameters"] = o.QueryParameters
	}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner := _CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner{}

	err = json.Unmarshal(data, &varCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner)

	if err != nil {
		return err
	}

	*o = CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner(varCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "cookies")
		delete(additionalProperties, "password")
		delete(additionalProperties, "queryParameters")
		delete(additionalProperties, "body")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner struct {
	value *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner
	isSet bool
}

func (v NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) Get() *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner {
	return v.value
}

func (v *NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) Set(val *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner(val *CreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) *NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner {
	return &NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner{value: val, isSet: true}
}

func (v NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDastRestProfileRequestConfigurationJsonStrAuthenticationPresetsInnerOneOfUsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


