/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](https://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9{}

// GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 struct for GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9
type GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 struct {
	Action ENUMSLEEP `json:"action"`
	AllowFailure *bool `json:"allow_failure,omitempty"`
	Seconds float32 `json:"seconds"`
	AdditionalProperties map[string]interface{}
}

type _GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9

// NewGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 instantiates a new GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9(action ENUMSLEEP, seconds float32) *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 {
	this := GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9{}
	this.Action = action
	this.Seconds = seconds
	return &this
}

// NewGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9WithDefaults instantiates a new GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9WithDefaults() *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 {
	this := GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9{}
	return &this
}

// GetAction returns the Action field value
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetAction() ENUMSLEEP {
	if o == nil {
		var ret ENUMSLEEP
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetActionOk() (*ENUMSLEEP, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) SetAction(v ENUMSLEEP) {
	o.Action = v
}

// GetAllowFailure returns the AllowFailure field value if set, zero value otherwise.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetAllowFailure() bool {
	if o == nil || IsNil(o.AllowFailure) {
		var ret bool
		return ret
	}
	return *o.AllowFailure
}

// GetAllowFailureOk returns a tuple with the AllowFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetAllowFailureOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowFailure) {
		return nil, false
	}
	return o.AllowFailure, true
}

// HasAllowFailure returns a boolean if a field has been set.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) HasAllowFailure() bool {
	if o != nil && !IsNil(o.AllowFailure) {
		return true
	}

	return false
}

// SetAllowFailure gets a reference to the given bool and assigns it to the AllowFailure field.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) SetAllowFailure(v bool) {
	o.AllowFailure = &v
}

// GetSeconds returns the Seconds field value
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value
// and a boolean to check if the value has been set.
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) GetSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seconds, true
}

// SetSeconds sets field value
func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) SetSeconds(v float32) {
	o.Seconds = v
}

func (o GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.AllowFailure) {
		toSerialize["allow_failure"] = o.AllowFailure
	}
	toSerialize["seconds"] = o.Seconds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 := _GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9{}

	err = json.Unmarshal(data, &varGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9)

	if err != nil {
		return err
	}

	*o = GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9(varGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "allow_failure")
		delete(additionalProperties, "seconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 struct {
	value *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9
	isSet bool
}

func (v NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) Get() *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 {
	return v.value
}

func (v *NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) Set(val *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9(val *GetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) *NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9 {
	return &NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9{value: val, isSet: true}
}

func (v NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProfile200ResponseConfigurationAuthenticationUsersInnerCredentialsActionsInnerOneOf9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


