/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// EnumGITLABGROUP the model 'EnumGITLABGROUP'
type EnumGITLABGROUP string

// List of Enum_GITLAB_GROUP
const (
	ENUMGITLABGROUP_GITLAB_GROUP EnumGITLABGROUP = "GITLAB_GROUP"
)

// All allowed values of EnumGITLABGROUP enum
var AllowedEnumGITLABGROUPEnumValues = []EnumGITLABGROUP{
	"GITLAB_GROUP",
}

func (v *EnumGITLABGROUP) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumGITLABGROUP(value)
	for _, existing := range AllowedEnumGITLABGROUPEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumGITLABGROUP", value)
}

// NewEnumGITLABGROUPFromValue returns a pointer to a valid EnumGITLABGROUP
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumGITLABGROUPFromValue(v string) (*EnumGITLABGROUP, error) {
	ev := EnumGITLABGROUP(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumGITLABGROUP: valid values are %v", v, AllowedEnumGITLABGROUPEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumGITLABGROUP) IsValid() bool {
	for _, existing := range AllowedEnumGITLABGROUPEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Enum_GITLAB_GROUP value
func (v EnumGITLABGROUP) Ptr() *EnumGITLABGROUP {
	return &v
}

type NullableEnumGITLABGROUP struct {
	value *EnumGITLABGROUP
	isSet bool
}

func (v NullableEnumGITLABGROUP) Get() *EnumGITLABGROUP {
	return v.value
}

func (v *NullableEnumGITLABGROUP) Set(val *EnumGITLABGROUP) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumGITLABGROUP) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumGITLABGROUP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumGITLABGROUP(val *EnumGITLABGROUP) *NullableEnumGITLABGROUP {
	return &NullableEnumGITLABGROUP{value: val, isSet: true}
}

func (v NullableEnumGITLABGROUP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumGITLABGROUP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

