/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
)

// checks if the CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests{}

// CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests struct for CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests
type CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests struct {
	HighNumberOfCustomScalars *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars `json:"high_number_of_custom_scalars,omitempty"`
	HighNumberOfPci *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars `json:"high_number_of_pci,omitempty"`
	HighNumberOfPii *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars `json:"high_number_of_pii,omitempty"`
	HighNumberOfPhi *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars `json:"high_number_of_phi,omitempty"`
	HighNumberOfSecrets *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars `json:"high_number_of_secrets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests

// NewCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests() *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests {
	this := CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests{}
	return &this
}

// NewCreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsWithDefaults instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsWithDefaults() *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests {
	this := CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests{}
	return &this
}

// GetHighNumberOfCustomScalars returns the HighNumberOfCustomScalars field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfCustomScalars() CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars {
	if o == nil || IsNil(o.HighNumberOfCustomScalars) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars
		return ret
	}
	return *o.HighNumberOfCustomScalars
}

// GetHighNumberOfCustomScalarsOk returns a tuple with the HighNumberOfCustomScalars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfCustomScalarsOk() (*CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars, bool) {
	if o == nil || IsNil(o.HighNumberOfCustomScalars) {
		return nil, false
	}
	return o.HighNumberOfCustomScalars, true
}

// HasHighNumberOfCustomScalars returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) HasHighNumberOfCustomScalars() bool {
	if o != nil && !IsNil(o.HighNumberOfCustomScalars) {
		return true
	}

	return false
}

// SetHighNumberOfCustomScalars gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars and assigns it to the HighNumberOfCustomScalars field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) SetHighNumberOfCustomScalars(v CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars) {
	o.HighNumberOfCustomScalars = &v
}

// GetHighNumberOfPci returns the HighNumberOfPci field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPci() CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars {
	if o == nil || IsNil(o.HighNumberOfPci) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars
		return ret
	}
	return *o.HighNumberOfPci
}

// GetHighNumberOfPciOk returns a tuple with the HighNumberOfPci field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPciOk() (*CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars, bool) {
	if o == nil || IsNil(o.HighNumberOfPci) {
		return nil, false
	}
	return o.HighNumberOfPci, true
}

// HasHighNumberOfPci returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) HasHighNumberOfPci() bool {
	if o != nil && !IsNil(o.HighNumberOfPci) {
		return true
	}

	return false
}

// SetHighNumberOfPci gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars and assigns it to the HighNumberOfPci field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) SetHighNumberOfPci(v CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars) {
	o.HighNumberOfPci = &v
}

// GetHighNumberOfPii returns the HighNumberOfPii field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPii() CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars {
	if o == nil || IsNil(o.HighNumberOfPii) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars
		return ret
	}
	return *o.HighNumberOfPii
}

// GetHighNumberOfPiiOk returns a tuple with the HighNumberOfPii field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPiiOk() (*CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars, bool) {
	if o == nil || IsNil(o.HighNumberOfPii) {
		return nil, false
	}
	return o.HighNumberOfPii, true
}

// HasHighNumberOfPii returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) HasHighNumberOfPii() bool {
	if o != nil && !IsNil(o.HighNumberOfPii) {
		return true
	}

	return false
}

// SetHighNumberOfPii gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars and assigns it to the HighNumberOfPii field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) SetHighNumberOfPii(v CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars) {
	o.HighNumberOfPii = &v
}

// GetHighNumberOfPhi returns the HighNumberOfPhi field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPhi() CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars {
	if o == nil || IsNil(o.HighNumberOfPhi) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars
		return ret
	}
	return *o.HighNumberOfPhi
}

// GetHighNumberOfPhiOk returns a tuple with the HighNumberOfPhi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfPhiOk() (*CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars, bool) {
	if o == nil || IsNil(o.HighNumberOfPhi) {
		return nil, false
	}
	return o.HighNumberOfPhi, true
}

// HasHighNumberOfPhi returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) HasHighNumberOfPhi() bool {
	if o != nil && !IsNil(o.HighNumberOfPhi) {
		return true
	}

	return false
}

// SetHighNumberOfPhi gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars and assigns it to the HighNumberOfPhi field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) SetHighNumberOfPhi(v CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars) {
	o.HighNumberOfPhi = &v
}

// GetHighNumberOfSecrets returns the HighNumberOfSecrets field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfSecrets() CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars {
	if o == nil || IsNil(o.HighNumberOfSecrets) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars
		return ret
	}
	return *o.HighNumberOfSecrets
}

// GetHighNumberOfSecretsOk returns a tuple with the HighNumberOfSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) GetHighNumberOfSecretsOk() (*CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars, bool) {
	if o == nil || IsNil(o.HighNumberOfSecrets) {
		return nil, false
	}
	return o.HighNumberOfSecrets, true
}

// HasHighNumberOfSecrets returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) HasHighNumberOfSecrets() bool {
	if o != nil && !IsNil(o.HighNumberOfSecrets) {
		return true
	}

	return false
}

// SetHighNumberOfSecrets gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars and assigns it to the HighNumberOfSecrets field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) SetHighNumberOfSecrets(v CreateBlstRestProfileRequestConfigurationJsonStrSecurityTestsHighNumberOfCustomScalars) {
	o.HighNumberOfSecrets = &v
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HighNumberOfCustomScalars) {
		toSerialize["high_number_of_custom_scalars"] = o.HighNumberOfCustomScalars
	}
	if !IsNil(o.HighNumberOfPci) {
		toSerialize["high_number_of_pci"] = o.HighNumberOfPci
	}
	if !IsNil(o.HighNumberOfPii) {
		toSerialize["high_number_of_pii"] = o.HighNumberOfPii
	}
	if !IsNil(o.HighNumberOfPhi) {
		toSerialize["high_number_of_phi"] = o.HighNumberOfPhi
	}
	if !IsNil(o.HighNumberOfSecrets) {
		toSerialize["high_number_of_secrets"] = o.HighNumberOfSecrets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) UnmarshalJSON(data []byte) (err error) {
	varCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests := _CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests{}

	err = json.Unmarshal(data, &varCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests)

	if err != nil {
		return err
	}

	*o = CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests(varCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "high_number_of_custom_scalars")
		delete(additionalProperties, "high_number_of_pci")
		delete(additionalProperties, "high_number_of_pii")
		delete(additionalProperties, "high_number_of_phi")
		delete(additionalProperties, "high_number_of_secrets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests struct {
	value *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests
	isSet bool
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) Get() *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests {
	return v.value
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) Set(val *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests(val *CreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) *NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests {
	return &NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests{value: val, isSet: true}
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrSecurityTests) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


