/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `X-ESCAPE-API-KEY` header. For example: `X-ESCAPE-API-KEY: YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the GeneratedOpenapiSpecDetailed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedOpenapiSpecDetailed{}

// GeneratedOpenapiSpecDetailed Detailed information about a generated openapi spec
type GeneratedOpenapiSpecDetailed struct {
	// The id of the generated openapi spec
	Id string `json:"id"`
	// The date and time the generated openapi spec was created
	CreatedAt string `json:"createdAt"`
	// The temporary signed url of the generated openapi spec
	TemporarySignedUrl string `json:"temporarySignedUrl"`
	AdditionalProperties map[string]interface{}
}

type _GeneratedOpenapiSpecDetailed GeneratedOpenapiSpecDetailed

// NewGeneratedOpenapiSpecDetailed instantiates a new GeneratedOpenapiSpecDetailed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedOpenapiSpecDetailed(id string, createdAt string, temporarySignedUrl string) *GeneratedOpenapiSpecDetailed {
	this := GeneratedOpenapiSpecDetailed{}
	this.Id = id
	this.CreatedAt = createdAt
	this.TemporarySignedUrl = temporarySignedUrl
	return &this
}

// NewGeneratedOpenapiSpecDetailedWithDefaults instantiates a new GeneratedOpenapiSpecDetailed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedOpenapiSpecDetailedWithDefaults() *GeneratedOpenapiSpecDetailed {
	this := GeneratedOpenapiSpecDetailed{}
	return &this
}

// GetId returns the Id field value
func (o *GeneratedOpenapiSpecDetailed) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GeneratedOpenapiSpecDetailed) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GeneratedOpenapiSpecDetailed) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GeneratedOpenapiSpecDetailed) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GeneratedOpenapiSpecDetailed) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GeneratedOpenapiSpecDetailed) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetTemporarySignedUrl returns the TemporarySignedUrl field value
func (o *GeneratedOpenapiSpecDetailed) GetTemporarySignedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemporarySignedUrl
}

// GetTemporarySignedUrlOk returns a tuple with the TemporarySignedUrl field value
// and a boolean to check if the value has been set.
func (o *GeneratedOpenapiSpecDetailed) GetTemporarySignedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemporarySignedUrl, true
}

// SetTemporarySignedUrl sets field value
func (o *GeneratedOpenapiSpecDetailed) SetTemporarySignedUrl(v string) {
	o.TemporarySignedUrl = v
}

func (o GeneratedOpenapiSpecDetailed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedOpenapiSpecDetailed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["temporarySignedUrl"] = o.TemporarySignedUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GeneratedOpenapiSpecDetailed) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"createdAt",
		"temporarySignedUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeneratedOpenapiSpecDetailed := _GeneratedOpenapiSpecDetailed{}

	err = json.Unmarshal(data, &varGeneratedOpenapiSpecDetailed)

	if err != nil {
		return err
	}

	*o = GeneratedOpenapiSpecDetailed(varGeneratedOpenapiSpecDetailed)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "temporarySignedUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGeneratedOpenapiSpecDetailed struct {
	value *GeneratedOpenapiSpecDetailed
	isSet bool
}

func (v NullableGeneratedOpenapiSpecDetailed) Get() *GeneratedOpenapiSpecDetailed {
	return v.value
}

func (v *NullableGeneratedOpenapiSpecDetailed) Set(val *GeneratedOpenapiSpecDetailed) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedOpenapiSpecDetailed) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedOpenapiSpecDetailed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedOpenapiSpecDetailed(val *GeneratedOpenapiSpecDetailed) *NullableGeneratedOpenapiSpecDetailed {
	return &NullableGeneratedOpenapiSpecDetailed{value: val, isSet: true}
}

func (v NullableGeneratedOpenapiSpecDetailed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedOpenapiSpecDetailed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


