/*
Escape Public API

This API enables you to operate [Escape](https://escape.tech/) programmatically.  All requests must be authenticated with a valid API key, provided in the `Authorization` header. For example: `Authorization: Key YOUR_API_KEY`.  You can find your API key in the [Escape dashboard](http://app.escape.tech/user/).

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner{}

// CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner struct for CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner
type CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner struct {
	Id string `json:"id"`
	Alert CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert `json:"alert"`
	Type EnumAPI `json:"type"`
	Seed []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner `json:"seed,omitempty"`
	Transform *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform `json:"transform,omitempty"`
	Detect []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner `json:"detect"`
	AdditionalProperties map[string]interface{}
}

type _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner(id string, alert CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert, type_ EnumAPI, detect []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner) *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner{}
	this.Id = id
	this.Alert = alert
	this.Type = type_
	this.Detect = detect
	return &this
}

// NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerWithDefaults instantiates a new CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerWithDefaults() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner {
	this := CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner{}
	return &this
}

// GetId returns the Id field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetId(v string) {
	o.Id = v
}

// GetAlert returns the Alert field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetAlert() CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert {
	if o == nil {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert
		return ret
	}

	return o.Alert
}

// GetAlertOk returns a tuple with the Alert field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetAlertOk() (*CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alert, true
}

// SetAlert sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetAlert(v CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerAlert) {
	o.Alert = v
}

// GetType returns the Type field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetType() EnumAPI {
	if o == nil {
		var ret EnumAPI
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetTypeOk() (*EnumAPI, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetType(v EnumAPI) {
	o.Type = v
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetSeed() []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner {
	if o == nil || IsNil(o.Seed) {
		var ret []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner
		return ret
	}
	return o.Seed
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetSeedOk() ([]CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner, bool) {
	if o == nil || IsNil(o.Seed) {
		return nil, false
	}
	return o.Seed, true
}

// HasSeed returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) HasSeed() bool {
	if o != nil && !IsNil(o.Seed) {
		return true
	}

	return false
}

// SetSeed gets a reference to the given []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner and assigns it to the Seed field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetSeed(v []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerSeedInner) {
	o.Seed = v
}

// GetTransform returns the Transform field value if set, zero value otherwise.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetTransform() CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform {
	if o == nil || IsNil(o.Transform) {
		var ret CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform
		return ret
	}
	return *o.Transform
}

// GetTransformOk returns a tuple with the Transform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetTransformOk() (*CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform, bool) {
	if o == nil || IsNil(o.Transform) {
		return nil, false
	}
	return o.Transform, true
}

// HasTransform returns a boolean if a field has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) HasTransform() bool {
	if o != nil && !IsNil(o.Transform) {
		return true
	}

	return false
}

// SetTransform gets a reference to the given CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform and assigns it to the Transform field.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetTransform(v CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransform) {
	o.Transform = &v
}

// GetDetect returns the Detect field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetDetect() []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner {
	if o == nil {
		var ret []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner
		return ret
	}

	return o.Detect
}

// GetDetectOk returns a tuple with the Detect field value
// and a boolean to check if the value has been set.
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) GetDetectOk() ([]CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Detect, true
}

// SetDetect sets field value
func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) SetDetect(v []CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInnerTransformTriggerInner) {
	o.Detect = v
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["alert"] = o.Alert
	toSerialize["type"] = o.Type
	if !IsNil(o.Seed) {
		toSerialize["seed"] = o.Seed
	}
	if !IsNil(o.Transform) {
		toSerialize["transform"] = o.Transform
	}
	toSerialize["detect"] = o.Detect

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"alert",
		"type",
		"detect",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner := _CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner{}

	err = json.Unmarshal(data, &varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner)

	if err != nil {
		return err
	}

	*o = CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner(varCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "alert")
		delete(additionalProperties, "type")
		delete(additionalProperties, "seed")
		delete(additionalProperties, "transform")
		delete(additionalProperties, "detect")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner struct {
	value *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner
	isSet bool
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) Get() *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner {
	return v.value
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) Set(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner(val *CreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner {
	return &NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner{value: val, isSet: true}
}

func (v NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlstRestProfileRequestConfigurationJsonStrCustomRulesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


