name: CLI Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: '1.25.9'

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
        golang:
          - '1.26'
          - '1.25.9'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          ref: ${{ github.head_ref || github.ref }}
      - uses: actions/checkout@v6
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.golang }}
      - name: Run tests
        run: go test ./...
